### ISSUE TITLE
error in HapCutToVcf

### ISSUE THREAD

**Issue by jaredo** [fulcrumgenomics/fgbio#113]
Hello! I am getting the following error when trying to run HapCutToVcf. I can share some test data but it is quite large.

```
$ java -jar /illumina/thirdparty/joconnell/fgbio/target/scala-2.11/fgbio-0.1.2-SNAPSHOT.jar HapCutToVcf -v ../NA12878.1000G.vcf -i na12878.output_haplotype_file  -o test.vcf
[2016/09/19 20:52:24 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.1.2-SNAPSHOT as joconnell@ukch-dev-lnt8-jo.local on JRE 1.8.0_40-b26
[2016/09/19 20:52:25 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0.07 minutes.
Exception in thread "main" java.lang.NumberFormatException: For input string: "1|0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30)
	at com.fulcrumgenomics.vcf.HapCutCall$$anonfun$9.apply(HapCutToVcf.scala:503)
	at com.fulcrumgenomics.vcf.HapCutCall$$anonfun$9.apply(HapCutToVcf.scala:503)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.fulcrumgenomics.vcf.HapCutCall.toVariantContext(HapCutToVcf.scala:503)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:269)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:240)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:240)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:111)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

just to check that my inputs are sane:

```
$ head na12878.output_haplotype_file
BLOCK: offset: 921 len: 195 phased: 2 SPAN: 1719 fragments 3
921	0	1	chr1	568214	C	T	1|0:255,0,255:84:26,28,14,16:127	0	0.000000	0.000000
1115	0	1	chr1	569933	G	A	1|0:221,0,255:97:36,36,15,10:127	0	0.000000	0.000000
******** 
BLOCK: offset: 1553 len: 59 phased: 2 SPAN: 2070 fragments 1
1553	0	1	chr1	724869	C	A	1|0:91,0,165:16:11,0,0,5:90	0	0.000000	-0.000087
1611	0	1	chr1	726939	G	C	1|0:255,0,255:52:13,11,7,21:127	0	0.000000	-0.000087
******** 
BLOCK: offset: 1952 len: 2 phased: 2 SPAN: 45 fragments 9
1952	0	1	chr1	749644	T	C	1|0:41,0,78:35:6,14,11,4:42	0	0.000000	0.000000

$ bcftools view -H ../NA12878.1000G.vcf | head
chr1	10539	.	C	A	0	.	DP=61;MQSB=0.805878;MQ0F=0;AC=0;AN=2;DP4=40,19,0,0;MQ=44	GT:PL:DP:DP4:GQ	0|0:0,178,255:59:40,19,0,0:255
chr1	10642	.	G	A	56	.	DP=20;MQSB=0.818182;MQ0F=0.7;AC=0;AN=2;DP4=2,11,0,0;MQ=0	GT:PL:DP:DP4:GQ	0|0:0,39,29:13:2,11,0,0:28
chr1	11008	.	C	G	54	.	DP=21;MQSB=1;MQ0F=1;AC=0;AN=2;DP4=12,9,0,0;MQ=0	GT:PL:DP:DP4:GQ	0|0:0,63,27:21:12,9,0,0:27
chr1	11012	.	C	G	52	.	DP=21;MQSB=1;MQ0F=1;AC=0;AN=2;DP4=12,8,0,0;MQ=0	GT:PL:DP:DP4:GQ	0|0:0,60,25:20:12,8,0,0:25
chr1	13011	.	T	G	0	.	DP=107;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.55873;BQB=1;MQ0F=0.635514;AC=0;AN=2;DP4=36,66,0,1;MQ=8	GT:PL:DP:DP4:GQ	0|0:0,255,196:103:36,66,0,1:255
chr1	13110	.	G	A	999	.	DP=51;MQSB=0.0687032;MQ0F=0.313726;AC=0;AN=2;DP4=7,42,0,0;MQ=15	GT:PL:DP:DP4:GQ	0|0:0,148,179:49:7,42,0,0:255
chr1	13116	.	T	G	97	.	DP=46;VDB=0.0517943;SGB=-0.693132;RPB=0.000248006;MQB=0.00218214;MQSB=0.29013;BQB=0.0112228;MQ0F=0.413043;AC=2;AN=2;DP4=3,7,3,31;MQ=11	GT:PL:DP:DP4:GQ	1|1:124,38,0:44:3,7,3,31:46
chr1	13118	.	A	G	94	.	DP=46;VDB=0.0555373;SGB=-0.693132;RPB=0.0001001;MQB=0.00136901;MQSB=0.197653;BQB=0.155903;MQ0F=0.456522;AC=2;AN=2;DP4=4,7,3,31;MQ=11	GT:PL:DP:DP4:GQ	1|1:121,35,0:45:4,7,3,31:42
chr1	13259	.	G	A	999	.	DP=65;MQSB=0.896401;MQ0F=0.707692;AC=0;AN=2;DP4=26,37,0,0;MQ=5	GT:PL:DP:DP4:GQ	0|0:0,190,135:63:26,37,0,0:255
chr1	13273	.	G	C	999	.	DP=55;MQSB=0.987527;MQ0F=0.709091;AC=0;AN=2;DP4=22,32,0,0;MQ=6	GT:PL:DP:DP4:GQ	0|0:0,163,132:54:22,32,0,0:255
```

**Comment by nh13** [comment]
@jaredo thanks for the very clear bug report.  I was able to reproduce the issue, which likely comes from the input to HapCut was a VCF with already phased genotypes, whereas the tool expected the variants not to be phased.  I have added support for the case you want to re-phase variants with HapCut, as the output of HapCut would includes the input genotypes.  Could you see if https://github.com/fulcrumgenomics/fgbio/pull/114 solves your issue?

**Comment by jaredo** [comment]
Thanks for the quick response. Yes, #114 fixes the issue.

**Comment by nh13** [comment]
👍 I will close this issue.  I am glad you are using this tool.
