### ISSUE TITLE
java.lang.NullPointerException error  - GroupReadsByUmi

### ISSUE THREAD

**Issue by mh1111** [fulcrumgenomics/fgbio#131]
Hi folks, 

I am getting the following error when I run GroupReadsByUmi:

###############################
[2016/11/21 15:32:07 | GroupReadsByUmi | Info] Sorted    76,000,000 record.  Elapsed time: 00:14:55s.  Time for last 1,000,000:   11s.  Last read position: chr2:198,257,003
[2016/11/21 15:32:19 | GroupReadsByUmi | Info] Sorted    77,000,000 record.  Elapsed time: 00:15:07s.  Time for last 1,000,000:   12s.  Last read position: chr7:148,525,795
[2016/11/21 15:32:24 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.
[2016/11/21 15:32:27 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 15.29 minutes.
Exception in thread "main" java.lang.NullPointerException
	at com.fulcrumgenomics.umi.GroupReadsByUmi$$anonfun$14.apply(GroupReadsByUmi.scala:477)
	at com.fulcrumgenomics.umi.GroupReadsByUmi$$anonfun$14.apply(GroupReadsByUmi.scala:477)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.assignUmiGroups(GroupReadsByUmi.scala:477)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:448)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
###############################

I could successfully run it on smaller BAM files, e.g., with 17M reads. Could it be because of the large size of my BAM file or some sort of memory issue?

Thanks for your continued support. 

Cheers,
MH

**Comment by mh1111** [comment]
I found the issue; UMI tags (RX) were missed in the BAM file after sorting and running SetMateInformation! I still do not know why this happened. Anyway, GroupReadsByUmi runs just fine on a BAM file with more than 77M reads!

**Comment by nh13** [comment]
@mh1111 I still think it's worth it to have a better error message when the UMI tag is missing.  Also, if you have a case where the `RX` tag disappears when running `SetMateInformation` that would seem not ideal, so I'd like to fix that too.  I am opening this and assigning it to myself.

**Comment by mh1111** [comment]
@nh13 that would be very nice to add such an error message. Honestly, I still do know why "RX" tag disappeared after running SetMateInformation. I have to add that it did not happen the second time I ran it.
Thank you very much for fixing this. 

Cheers,
MH

**Comment by nh13** [comment]
@mh1111 I don't see why in the code `SetMateInformation` would remove it.  A better error message can be found here: https://github.com/fulcrumgenomics/fgbio/pull/132
