### ISSUE TITLE
UMI alignment workflow

### ISSUE THREAD

**Issue by jasonwalker80** [fulcrumgenomics/fgbio#271]
I've used the DemuxFastq tool to perform the demux with UMIs in both FASTQ and BAM output format. I then align the output FASTQ (or unaligned BAM converted to FASTQ) with BWA-MEM 0.7.15. I did not expect the UMI info/tag to be retained in the output alignments other than in the read names from the input FASTQ.

Now, I'm unsure what the workflow should be to add the UMI info as a tag to the aligned BAM, either from the read names or from other files. I was planning to use AnnotateBamWithUmis. After some initial testing, that tool is expecting the UMI to be in a separate FASTQ file. The DemuxFastq command does NOT produce a UMI FASTQ, only the paired R1 and R2 FASTQ with the UMI in the read name.

I'm sure I can get this to work with a little file format manipulation or pulling the UMI from the read names to another FASTQ format file. Before I do that, I wanted to check with the authors and maintainers of fgbio to see if I'm missing something. Is there a smoother workflow that would avoid writing my own short script or using a combination of bash commands to get the UMI info into the appropriate BAM tags?

Also, please let me know if there is a better place for this support question, ex. BioStars, etc.

**Comment by nh13** [comment]
@jasonwalker80 thanks for taking the time to try out `DemuxFastqs`, I can certainly try to help you here.

 You can specify the read structure in `DemuxFastqs` to include the molecular barcode in addition to the sample barcode (ex. `8B8M100T`, gives 8bp of sample barcode, 8bp of molecular barcode, and 100bp of template).  If you output to BAM, the molecular barcode will be stored in the `RX` tag by default (see `--umi-tag`).

  In our own [workflows](https://github.com/fulcrumgenomics/dagr/blob/master/tasks/src/main/scala/dagr/tasks/bwa/Bwa.scala), we take the unmapped BAM for the sample, pipe it into `bwa` using Picard's `SamToFastq` tool, then pipe the output of `bwa` into Picard's `MergeBamAlignment` tool.  The `MergeBamAlignment` tool takes both the unmapped BAM **and** the mapped BAM coming from BWA, and produces a coordinate sorted BAM with all the original tags found in the unmapped BAM (since BWA doesn't retain that information).  This gives you a mapped BAM with the UMIs in the correct place (i.e. `RX` tag).   It also cleans up a few things from earlier versions of `bwa`, like mappings that go past the end of chromosomes.  In general, we recommend staying away from storing FASTQs and use it instead as an temporary or intermediate format.

The mapped BAM with UMIs allows you to use tools like Picard's `MarkDuplicates` (see the `BARCODE_TAG` option) and leverage the UMIs to better discriminate between PCR duplicates and those reads that happen by chance to map to the same genomic location, which happens often for high coverage (>100x) samples.  For other library preparations like Duplex Sequencing or Long Molecule Assembly (ex. 10x or iGenomX), this allows you to call consensus reads from the reads with the same UMI and genomic location (details omitted here).

Please let us know if you find this helpful and feel free to ask questions here, Biostars, Seqanswers, or elsewhere, and we'll be happy to respond, though if you choose the latter options, make sure to link an issue here, as we are more likely to see it.

**Comment by jasonwalker80** [comment]
No need to reopen this, but I did find an issue with the sort order of the `DemuxFastq` and the output of BWA. My command was something like:
```
java -jar picard.jar SamToFastq I=DemuxFastq.bam INTERLEAVE=true FASTQ=/dev/stdout | bwa mem -K 100000000 -t 8 -p -R "${RG_STRING}" ${REF_FASTA} /dev/stdin | java -jar picard.jar MergeBamAlignment ALIGNED=/dev/stdin UNMAPPED=DemuxFastq.bam O=${ALIGNED_BAM_FILE} R=${REF_FASTA}
```
A warning from Picard which triggers errexit when set:
```
WARNING	2017-08-15 11:57:01	SamAlignmentMerger	Exception merging bam alignment - attempting to sort aligned reads and try again: Underlying iterator is not queryname sorted: K00193:201:HHV33BBXX:1:1101:31872:1402 2/2 151b aligned read. > K00193:201:HHV33BBXX:1:1101:22891:1420 1/2 151b aligned read.
```

If errexit is not set it runs but fails at the end with:
```
Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (K00193:201:HHV33BBXX:1:1101:10003:10141) is behind the unmapped reads (K00193:201:HHV33BBXX:1:1101:31872:1402)
	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:451)
	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:157)
	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:266)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

Sorting the DemuxFastq.bam with `java -jar picard.jar SortSam I=DemuxFastq.bam O=QuerynameDemuxFastq.bam SORT_ORDER=queryname` seems to do the trick.

Should I submit a separate issue for the sorting issue? Or is this an omitted piece of the workflow? Or am I experiencing some other issue, in other words, should this work without a `SortSam` of the `DemuxFastq` BAM file?

**Comment by nh13** [comment]
@jasonwalker80 
(1) yes, please file an issue.
(2) my initial take is that it is due to the difference between how `fgbio` and `Picard` sort by `queryname`, with neither being correct or incorrect according to the SAM specification.  In fact, if you sort by `queryname` using `samtools sort`, you'd also get this error.  A few solutions we could consider are:

  1. Add a "picard-queryname" sort order to `fgbio` (or `fgbio-queryname` to `picard`).
  2. Add an option in `picard` to not check the input sort order in `MergeBamAlignment`.

If you could open the new issue, we can discuss further there.
