### ISSUE TITLE
fgbio queryname sort order and Picard compatibility 

### ISSUE THREAD

**Issue by jasonwalker80** [fulcrumgenomics/fgbio#272]
I found an issue with the sort order of the `DemuxFastq` and the output of `BWA` going into `MergeBamAlignment`. My example command:
```
java -jar picard.jar SamToFastq I=DemuxFastq.bam INTERLEAVE=true FASTQ=/dev/stdout | bwa mem -K 100000000 -t 8 -p -R "${RG_STRING}" ${REF_FASTA} /dev/stdin | java -jar picard.jar MergeBamAlignment ALIGNED=/dev/stdin UNMAPPED=DemuxFastq.bam O=${ALIGNED_BAM_FILE} R=${REF_FASTA}
```
A warning from Picard which triggers errexit when set:
```
WARNING	2017-08-15 11:57:01	SamAlignmentMerger	Exception merging bam alignment - attempting to sort aligned reads and try again: Underlying iterator is not queryname sorted: K00193:201:HHV33BBXX:1:1101:31872:1402 2/2 151b aligned read. > K00193:201:HHV33BBXX:1:1101:22891:1420 1/2 151b aligned read.
```

If errexit is not set it runs but fails at the end with:
```
Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (K00193:201:HHV33BBXX:1:1101:10003:10141) is behind the unmapped reads (K00193:201:HHV33BBXX:1:1101:31872:1402)
	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:451)
	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:157)
	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:266)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

Sorting the DemuxFastq.bam with `java -jar picard.jar SortSam I=DemuxFastq.bam O=QuerynameDemuxFastq.bam SORT_ORDER=queryname` seems to do the trick. UPDATE, I also used Picard SortSam on the BWA aligned BAM to fix this issue. I have not tested this using the raw output (eg. native sort order) from BWA. I've always presumed the order was the same as the input, but I can see with multi-threading how this may be disrupted.

See #271 for additional background and some potential explanations from @nh13.

**Comment by nh13** [comment]
Looks like the `queryname` order in `fgbio` is compatible with `picard`, and it was as simple as specifying the output sort order to `DemuxFastqs`, which is now `queryname` by default.  Thanks for reporting!
