### ISSUE TITLE
GroupReadsByUmi fails with "Reads out of order" in SamWriter

### ISSUE THREAD

**Issue by angadps** [fulcrumgenomics/fgbio#313]
I get the stack trace below when running the GroupReadsByUmi tool. The exception statement reads:

**Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ readID1/1 + readID2/2**

readID1 and readID2 obviously are different read IDs

[2017/11/11 14:32:12 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.
[2017/11/11 14:33:38 | SamWriter | Info] Wrote      2,000,000 records.  Elapsed time: 00:01:25s.  Time for last 2,000,000:   71s.  Last read position: chr1:11,297,872
[2017/11/11 14:34:38 | SamWriter | Info] Wrote      4,000,000 records.  Elapsed time: 00:02:25s.  Time for last 2,000,000:   59s.  Last read position: chr1:17,084,921
[2017/11/11 14:35:25 | SamWriter | Info] Wrote      6,000,000 records.  Elapsed time: 00:03:12s.  Time for last 2,000,000:   46s.  Last read position: chr1:40,778,323
[2017/11/11 14:36:09 | SamWriter | Info] Wrote      8,000,000 records.  Elapsed time: 00:03:56s.  Time for last 2,000,000:   44s.  Last read position: chr1:62,910,334
[2017/11/11 14:36:52 | SamWriter | Info] Wrote     10,000,000 records.  Elapsed time: 00:04:39s.  Time for last 2,000,000:   43s.  Last read position: chr1:110,200,158
[2017/11/11 14:37:33 | SamWriter | Info] Wrote     12,000,000 records.  Elapsed time: 00:05:20s.  Time for last 2,000,000:   40s.  Last read position: chr1:120,611,576
[2017/11/11 14:38:13 | SamWriter | Info] Wrote     14,000,000 records.  Elapsed time: 00:06:00s.  Time for last 2,000,000:   39s.  Last read position: chr1:152,279,686
[2017/11/11 14:38:49 | SamWriter | Info] Wrote     16,000,000 records.  Elapsed time: 00:06:36s.  Time for last 2,000,000:   36s.  Last read position: chr1:152,327,926
[2017/11/11 14:39:30 | SamWriter | Info] Wrote     18,000,000 records.  Elapsed time: 00:07:17s.  Time for last 2,000,000:   41s.  Last read position: chr1:162,249,814
[2017/11/11 14:40:12 | SamWriter | Info] Wrote     20,000,000 records.  Elapsed time: 00:07:59s.  Time for last 2,000,000:   42s.  Last read position: chr1:186,307,216
[2017/11/11 14:40:48 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 122.62 minutes.
**Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ readID1/1 + readID2/2**
        at scala.Predef$.assert(Predef.scala:219)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$10(GroupReadsByUmi.scala:422)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$10$adapted(GroupReadsByUmi.scala:421)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:421)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

The original bam file was prepared using some standard GATK guidelines:
bwa-mem --> IndelRealignment --> BQSR

Duplicates were NOT marked. The BQSR bam was validated using ValidateSamFile and it checked out with no errors. The validated bam was passed through CorrectUmis before passing through GroupReadsByUmi. fgbio version used is 0.3.0.

$JAVA -jar $FGBIO --tmp-dir=/tmp CorrectUmis -i BARCODE.cleaned.bam -o BARCODE.corrected.bam -m 1 -d 2 -r BARCODE.rejected.bam -M BARCODE.metrics.txt -U umisFixed.txt -t BC

$JAVA -jar $FGBIO --tmp-dir=/tmp --log-level=Debug GroupReadsByUmi -i BARCODE.corrected.bam -o BARCODE.grouped.bam -f family.count.txt -t BC -s edit -e 2

Is this a known/previously encountered issue?

**Comment by nh13** [comment]
@angadps any chance you could print out the reads with name "readID1" and "readID2"?  Something like `samtools view in.bam | grep readID1` should get the rads.  I am betting that somehow one of the ends for `readID1` read pair is being filtered out but not the other (perhaps the `MQ` tag is missing?).

**Comment by angadps** [comment]
@nh13 below are the 4 lines for the two read pairs:

read1ID 147     chr1    152127815       60      8S104M  =       152127818       -101    CAGTGTTATGTGATTGAATATAGTGGGAACTCTGGCCTTGTCTGTCTGTCTGACCATAATGATAGCTCTGGCCTTGTCTGTCTGTCTGACCGTAGTGGGAACTCTGGCCTTG       ###BCDCEF-AEFFGEDECFCEEGDDECCFDFFDBEFEFEDFFEDFFEDFFECEGECCEFEECEFFDFFDFEFEFEDFFEDFFDDFFDCE=DBDDECCDBBEBDDBDBA@A@        BC:Z:ACAGTGTTATAA-CTTGTACGTTAT  MC:Z:101M11S  BD:Z:KKKKPOOQMLOPNMOMKKLKLNJOKLLLNJJOONMLKKJNINJNINJNINMMLMNJJJMMNJKNOIINNMLKJKJNINJNINJNINMMLKLLKMINJKKKMIIOOONNKLKK    MD:Z:104        RG:Z:AMP.1      BI:Z:OOOOWTVWSRVUURUPPPRPRTPSKOOPUMNRSQRONOOQNQOPMQNPMQRQRQTNONRRRNPSPLMQRPQNMONPMQNPMQNPMQQPRMPPPRNRJNNOTLNRSQSPNPOO  NM:i:0  MQ:i:60 AS:i:104        XS:i:0

read2ID        97      chr1    152127817       45      100M4D12M       =       152128095       369     TGATTGAATATAGTGGGAACTCTGGCCTTGTCTGTCTGTCTGACCATAATGATAGCTCTGGCCTTGTCTGTCTGTCTGACCATAGTGTGAACTCTGGCCTTGTTTGTCTGAC       4?=@BFC>CCE;D<G2@4EE51A@@.-A@G<065<9A5C1F4?.EFB=F3D#############################################################        BC:Z:GCCAATTTATAA-CTTGTACGTTAT     **OC:Z:112M**        BD:Z:KKONNOQMNLKLONKNJLLLMHIMMLMKILJMIMJMIMJMIMNNMNMKJLNJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKLLLLLMMMNNOPKKKK   RG:Z:AMP.1      BI:Z:OOTSPSTOSQNPRTOQJONPRLLPQPPOMQOQLPOQLPOQLPSPPRRPNRTNNNNNNNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOOOPPPPPPPPQQQQRRSTTVOOOO  NM:i:7  AS:i:95 XS:i:70

read1ID 99      chr1    152127818       60      101M11S =       152127815       101     GATTGAATATAGTGGGAACTCTGGCCTTGTCTGTCTGTCTGACCATAATGATAGCTCTGGCCTTGTCTGTCTGTCTGACCGTAGTGGGAACTCTGGCCTTGATAACGTACAA       A@@>ECEE@ECFCGEEDEEEEEGEFDECGCEEGCEEGCEEHDEEGECEFHDFDGFFFFHEGDFDHDEFGDFFHDFFHEFE>CDGDHFF@FFFFFHFGEFDGC@AC/=A>ABA        BC:Z:ACAGTGTTATAA-CTTGTACGTTAT  MC:Z:8S104M   BD:Z:KKNKPQNNMKLONKNJLLLNHIMMLMKILJMIMJMIMJMIMNNMNMKJLNNMKNONHIMMLMKILJMIMJMINKNJNOONKOMONKNJLLLNIJNNNOMKNQPNNOQTMMKL    MD:Z:101        RG:Z:AMP.1      BI:Z:OOSOSUOSQOPRTOQJONPRLLPQQOOMQOQLPOQLPOQLPSPPRRPNRTSRPRPSLLPQQPOMQOQLPPRMQPRMQTQQPTSSUPRKPORTNNRSSRRPTVVTSVV[SQOP  NM:i:0  MQ:i:60 AS:i:101        XS:i:19

read2ID        145     chr1    152128095       36      21S91M  =       152127817       -369    GATAATACTGTTAACTTTTGCCTTGTCTGTCTGTTTTACCATAGTGTGAACTCTGGCCTTGTTTGTCTGGCTGACTGTAGTGGGAACTCTGGCCTTGTCTGTCTGTCTGACC       ######################################################D7/@C2EBEFED3BDCFDECFF-CEEFD@;2<FCFFDEDDDED@DE?CDDCB?C@><<        BC:Z:GCCAATTTATAA-CTTGTACGTTAT  MC:Z:100M4D12M BD:Z:KKKKOONNMMLLLLLLKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJJJJMLKJKJKCKJNINNMONMMMNJLKMINJKKKMIINNMLKJKJNINJNINKOKPPNMKK   MD:Z:11A1C11G65 RG:Z:AMP.1      BI:Z:OOOOUTTSSRRQQQQPPPPPPPPOOOOOOOOOOOOOONOOONONNNNNNNNNNNPQNMONPGONPMQRPPQRQTQNPPRNRJNNOTKLQRPQNMONPMQNPMROQNSTRSOO  NM:i:3  MQ:i:45 AS:i:76 XS:i:54

So MQ tag does seem missing for read2ID and so is the Mate Cigar, but Original Cigar is present. Liked I said, the bam file did pass ValidateSamFile but perhaps the tool does not look for optional tags for consistency?

**Comment by nh13** [comment]
@angadps I think the issue is that "read2ID" is missing the "MQ" optional SAM tag.  We do say that the `MQ` tag is required in the tool's description, and filter out any read that do not have it.  I have to say it's odd that one end does, and the other end doesn't.  We recommend using `MergeBamAlignment` to ensure that the recommended tags are present in the output of the aligner.  In this case, you can try running fgbio's `SetMateInformation` to add the "MQ".  Let me know if that works.

**Comment by angadps** [comment]
@nh13 Thanks for the suggestion. I notice the SetMateInformation tool requires reads to be present in query-name order, which is a huge operation for the size of the bam file that I am working with. I'm going to do that and confirm whether the tool works well with the fixed reads or not. I'll keep you updated once I have that information.

Thank you.

**Comment by angadps** [comment]
@nh13 I ran SetMateInformation but it did not populate the MQ tag for the respective read. GroupReadsByUmi failed again. Then I decided to filter out all reads that are missing an MQ tag. I ran GroupReadsByUmi on the new bam file and I see the exact same error as above. At this point I'm starting to believe there is something else going on here. I also notice that a substantial percentage of the reads in my bam file do not contain an MQ tag to begin with. While some of those may be filtered out for other reasons, some of them may have passed through GroupReadsByUmi successfully before it fails on these particular reads.

It is not most important for me to get this working at the moment but obviously useful to have it so. If you do have additional suggestions please let me know.

Thank you.

**Comment by tfenne** [comment]
@angadps Any chance you can reproduce this error with a small BAM file with just a handful of reads in it, and that you could then share the file with us?  That way we could try and recreate the error on our end and see what's going on.

**Comment by angadps** [comment]
@tfenne At this point I can only do a simple extraction of reads loosely around the region where I see the failure and share that with you. Reproducing the error on this smaller bam file and testing before I share can take some time and is going to be difficult. I wouldn't bother you again until I can do that next.

**Comment by tfenne** [comment]
@angadps No worries.  I'm happy to help, but I think we're at a point where I need to be able to reproduce the issue.  If you're comfortable sharing the reads in that region, in BAM format, please do so.

**Comment by nh13** [comment]
@angadps closing due to lack of activity.
