### ISSUE TITLE
Consensus base quality and issue with FilterConsensusReads

### ISSUE THREAD

**Issue by mh1111** [fulcrumgenomics/fgbio#320]
Hi folks, 

I am trying to filter consensus reads in `1.2.bam`, generated by CallMolecularConsensusReads, using FilterConsensusReads. Header and four first lines of `1.2.bam` are:

```
$ samtools view -H 1.2.bam 
@HD	VN:1.5	SO:queryname	GO:none
@RG	ID:A
@CO	Read group A contains consensus reads generated from 0 input read groups.

$ samtools view 1.2.bam | head -4
1.2:100	77	*	0	0	*	*	0	0	ATGGCCTTAGTGCACTGCAGAGGCCCCCAGGGTTCCTCCTCCAACCACCTTGCAGAGTGAGCTGCCTCCCAGAGCTCCCAGAGCTCCCAGTGCAGAGGGAGGGGATGAGTGATNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN	cD:i:5	cE:f:0	RG:Z:A	MI:Z:100	cM:i:5	RX:Z:TACCGCCGGGGAGAGC	cd:B:s,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5	ce:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1.2:100	141	*	0	0	*	*	0	0	GAGCCCAGGAGTTTGAGGCTGCAGTGAGCTATGACTGTGCCCCTGCACTCCAGCCTGGGTGACAGAGTGAGACCCTGTCTCAAAACAAAACAAACAAAAATAAAAATGAAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN	cD:i:5	cE:f:0	RG:Z:A	MI:Z:100	cM:i:5	RX:Z:TACCGCCGGGGAGAGC	cd:B:s,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5	ce:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1.2:1000	77	*	0	0	*	*	0	0	AGCCATCGTGCCTGGCTGCCTGGCCTTCAGTCCTCATTTCTGATATACCACCTCTCTATTTGGCATTTTCACCTAGCTCAAAAAGTCAGTTCCTGATAGCATTGTTAACATAGC	NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN	cD:i:6	cE:f:0	RG:Z:A	MI:Z:1000	cM:i:6	RX:Z:GATTGGTAGTTGCTCA	cd:B:s,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6	ce:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1.2:1000	141	*	0	0	*	*	0	0	GAACCCAGGAGGCGGAGGTTGCAGTGAGCCAAGATCGTGCCACTGCACTCCAGCCTGGGCAATAGACCCTGCCAGTTTCTGCAAGCTGTCAGCACAGGCTAGCTATGTTAACAA	NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN	cD:i:6	cE:f:0.00292398	RG:Z:A	MI:Z:1000	cM:i:6	RX:Z:GATTGGTAGTTGCTCA	cd:B:s,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6	ce:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```
it would be great if you could please let me know about your inputs on:

Q1. Why all the base qualities are capped to 45, the default value of  --error-rate-pre-umi? Do I need to use a value other than the default --error-rate-pre-umi for my data? Or does it simply mean that the bases are highly accurate calls and all the qualities are capped?

Options used for CallMolecularConsensusReads: `-N 0 -m 0 -M 5`

Q2. When I want to filter reads in `1.2.bam` via 
```
FilterConsensusReads -i 1.2.bam -o 1.2.filtered.bam -r hg19.fa --min-reads 5 --min-base-quality 0 --max-read-error-rate 0 --max-base-error-rate 0.1 --max-no-call-fraction 0.1
```

I get the following error:

```
[2017/11/16 13:24:51 | FgBioMain | Info] FilterConsensusReads failed. Elapsed time: 0.04 minutes.
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. @RG line missing SM tag. Line:
@RG	ID:A; File 1.2.bam; Line number 2
	at htsjdk.samtools.SAMTextHeaderCodec.reportErrorParsingLine(SAMTextHeaderCodec.java:265)
	at htsjdk.samtools.SAMTextHeaderCodec.access$200(SAMTextHeaderCodec.java:43)
	at htsjdk.samtools.SAMTextHeaderCodec$ParsedHeaderLine.requireTag(SAMTextHeaderCodec.java:346)
	at htsjdk.samtools.SAMTextHeaderCodec.parseRGLine(SAMTextHeaderCodec.java:175)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:108)
	at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:667)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:298)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:176)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:385)
	at com.fulcrumgenomics.bam.api.SamSource$.apply(SamSource.scala:67)
	at com.fulcrumgenomics.umi.FilterConsensusReads.execute(FilterConsensusReads.scala:170)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

```
Removing `@RG` line does not work either as it seems ID:A is used:
```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 1, Read name 1.2:100, RG ID on SAMRecord not found in header: A
```

thank you in advance for your inputs. 

cheers,
MH

**Comment by mh1111** [comment]
Hi @tfenne 

Thank you so much for your detailed and prompt response. All the issues resolved. 

Best,
MH
