### ISSUE TITLE
DemuxFastqs OutOfMemoryError

### ISSUE THREAD

**Issue by gshiba** [fulcrumgenomics/fgbio#326]
Out of memory error with `DemuxFastqs`. I did not see anything re memory constraints in the documentation, but if this is expected behavior, feel free to close.

```bash

$ fgbio --version  # conda isntallation
Version: 0.4.0

$ cat samples.csv
Sample_Barcode,Sample_ID,Sample_Name,Library_ID,Description
AGACGTCT,foo,S1,,
TTGATCAA,bar,S2,,
GAGCGCTC,baz,S3,,

$ fgbio DemuxFastqs -i ../r1.fastq.gz ../i1.fastq.gz ../i2.fastq.gz ../r2.fastq.gz -o demuxed --read-structures 3M1S+T 4B4M 4B 3M1S+T --metadata samples.csv
[2017/11/17 15:27:54 | DemuxFastqs | Info] Assuming input metadata file is simple CSV file.
[2017/11/17 15:27:54 | FgBioMain | Info] Executing DemuxFastqs from fgbio version 0.4.0 as gshiba@xyz on JRE 1.8.0_121-b15 with snappy
[2017/11/17 15:27:54 | DemuxFastqs | Warning] Making ambiguous determination about fastq's quality encoding; possible encodings: Standard, Solexa, Illumina.
[2017/11/17 15:27:54 | DemuxFastqs | Info] Auto-detected quality format as: Standard
[2017/11/17 15:28:03 | DemuxFastqs | Info] processed     1,000,000 records.  Elapsed time: 00:00:08s.  Time for last 1,000,000:    8s.  Last read position: */*
[2017/11/17 15:28:18 | DemuxFastqs | Info] processed     2,000,000 records.  Elapsed time: 00:00:23s.  Time for last 1,000,000:   15s.  Last read position: */*
[2017/11/17 15:28:32 | FgBioMain | Info] DemuxFastqs failed. Elapsed time: 0.66 minutes.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:177)
        at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:44)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$Lambda$36/1028780142.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at com.fulcrumgenomics.fastq.FastqDemultiplexer.matchSampleBarcode(DemuxFastqs.scala:609)
        at com.fulcrumgenomics.fastq.FastqDemultiplexer.demultiplex(DemuxFastqs.scala:649)
        at com.fulcrumgenomics.fastq.DemuxFastqs$.$anonfun$demultiplexingIterator$4(DemuxFastqs.scala:157)
        at com.fulcrumgenomics.fastq.DemuxFastqs$$$Lambda$499/255041198.apply(Unknown Source)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at com.fulcrumgenomics.fastq.DemuxFastqs.execute(DemuxFastqs.scala:379)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

$ ls ../*.fastq.gz | parallel -k 'echo -n "{} -- "; zcat {} | wc -l'
../i1.fastq.gz -- 4632128
../i2.fastq.gz -- 4632128
../r1.fastq.gz -- 4632128
../r2.fastq.gz -- 4632128  # ~ 1M reads, which is not very many...
```

Thanks

**Comment by gshiba** [comment]
I was able to get around this with `fgbio -Xmx4g DemuxFastqs ...`

**Comment by tfenne** [comment]
@gshiba That's the right answer.  I just looked at the wrapper script in bioconda and the default memory limit is 1GB, which is too low for most of our tools.  I've just pushed a small PR there to up it to 4GB to avoid this kind of confusion in future.
