### ISSUE TITLE
Version 0.4.0 option to output consensus reads that are formed from only a single strand in CallDuplexConsensusReads 

### ISSUE THREAD

**Issue by dilmiperera** [fulcrumgenomics/fgbio#349]
Hi Tim and Nils,

I've switched to the latest version of fgbio (0.4.0) and one of the new options in this version is the option to output consensus reads that are formed from only a single strand in the CallDuplexConsensusReads method. I was wondering what parameter/argument I need to specify to get this option? It doesn't mention this is the description of the method parameters/arguments.

Thanks,
Dilmi

**Comment by nh13** [comment]
@dilmiperera the `--min-reads` option to `CallDuplexConsensusReads` is where you want to focus your attention.  Take a look at the documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/CallDuplexConsensusReads.html

> The first value applies to the final consensus read, the second value to one single-strand consensus, and the last value to the other single-strand consensus. 

Therefore, to require only a single strand, you should specify `--min-reads 1 1 0`, which requires one read for the final consensus, one read for one of the two single-strand consensuses, and zero reads for the other single-strand consensus. 

Please reply here if that answers your question.

**Comment by dilmiperera** [comment]
Yes this is exactly what I was looking for. 

Thank you very much for your quick response.

Dilmi

**Comment by dilmiperera** [comment]
@nh13 How does it work in the FilterConsensusReads step for this option? I tried using the same -M 1 1 0 but I'm getting an error.

[2018/01/10 06:55:21 | FgBioMain | Info] Executing FilterConsensusReads from fgbio version 0.4.0 as xxxxxx@xxxx.xxxx.private on JRE 1.8.0_144-b01 with snappy
[2018/01/10 06:55:21 | FilterConsensusReads | Info] Filtering reads.
[2018/01/10 06:55:21 | FgBioMain | Info] FilterConsensusReads failed. Elapsed time: 0.06 minutes.
Exception in thread "main" java.lang.NullPointerException
	at com.fulcrumgenomics.umi.FilterConsensusReads.$anonfun$filterDuplexConsensusRead$5(FilterConsensusReads.scala:325)
	at com.fulcrumgenomics.commons.CommonsDef.forloop(CommonsDef.scala:210)
	at com.fulcrumgenomics.umi.FilterConsensusReads.filterDuplexConsensusRead(FilterConsensusReads.scala:323)
	at com.fulcrumgenomics.umi.FilterConsensusReads.filterRecord(FilterConsensusReads.scala:253)
	at com.fulcrumgenomics.umi.FilterConsensusReads.$anonfun$execute$1(FilterConsensusReads.scala:195)
	at com.fulcrumgenomics.umi.FilterConsensusReads.$anonfun$execute$1$adapted(FilterConsensusReads.scala:180)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.bam.Bams$$anon$1.foreach(Bams.scala:217)
	at com.fulcrumgenomics.umi.FilterConsensusReads.execute(FilterConsensusReads.scala:180)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by nh13** [comment]
@dilmiperera I am investigating your issue.

**Comment by dilmiperera** [comment]
@nh13 Thanks!

**Comment by nh13** [comment]
@dilmiperera a potential bug fix is in #351.

**Comment by dilmiperera** [comment]
@nh13 The bug fix worked. Thanks again!

**Comment by nh13** [comment]
👍

**Comment by dilmiperera** [comment]
Hi Nils,

I wonder if its possible to have a different filtering criteria for the true duplex families and the consensus reads called from only a single strand in the FilterConsensusReads step (after using the option to output consensus reads that are formed from only a single strand in CallDuplexConsensusReads)? What we want is all the duplex families that have a minimum depth of one on each strand (M=2 1 1) and for the families with only one strand filtered at a minimum depth of 3. Is this possible? 

Right now we're using (M=2 1 0) which allows us to filter duplex families that have at minimum depth of one on each strand and single strand only families that have a minimum depth of 2.

Thanks,
Dilmi

**Comment by nh13** [comment]
@dilmiperera my suggestion would be as follows:
1. Get all the duplex families with a minimum of one read on each strand like you said with (M=2 1 1).
2. Get all the single-strand-only consensus calls by keeping only reads with a b-strand depth of zero (ex. `samtools view -h <consensus.unfiltered.bam> | egrep "(^@|bD:i:0)" | samtools view -Sb - > <consensus.unfiltered.single-strand.bam`.  NB: see the [consensus tags](https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/umi/ConsensusTags.scala) stored in the BAM file that can be used to filter the data.
3. Use the BAM from (2) and filter using (M=3 3 0).

**Comment by dilmiperera** [comment]
@nh13 
Great! Thank you once again for your quick response.

**Comment by dilmiperera** [comment]
@nh13 
I tried your suggestion for getting single strand reads with a minimum of 3 supporting reads but I get the following error when I do step 3 (Use the BAM from (2) and filter using (M=3 3 0))

[2018/07/15 16:05:40 | FgBioMain | Info] Executing FilterConsensusReads from fgbio version 0.5.0-SNAPSHOT as xxxxx@xxxx.cbio.private on JRE 1.8.0_144-b01 with snappy
[2018/07/15 16:05:40 | FilterConsensusReads | Info] Filtering reads.
[2018/07/15 16:05:43 | FgBioMain | Info] FilterConsensusReads failed. Elapsed time: 0.11 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Paired read missing R2: 4:10003
	at scala.Predef$.require(Predef.scala:277)
	at com.fulcrumgenomics.umi.FilterConsensusReads.$anonfun$execute$1(FilterConsensusReads.scala:184)
	at com.fulcrumgenomics.umi.FilterConsensusReads.$anonfun$execute$1$adapted(FilterConsensusReads.scala:182)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.bam.Bams$$anon$1.foreach(Bams.scala:217)
	at com.fulcrumgenomics.umi.FilterConsensusReads.execute(FilterConsensusReads.scala:182)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

It looks like a paired read is missing. Could it be from step 2? (samtools view -h <consensus.unfiltered.bam> | egrep "(^@|bD:i:0)" | samtools view -Sb - > <consensus.unfiltered.single-strand.bam>) 

Thanks,
Dilmi
