### ISSUE TITLE
UnsupportedOperationException when using TrimPrimers

### ISSUE THREAD

**Issue by scottrk2** [fulcrumgenomics/fgbio#392]
fgbio version: 0.5.0

java JVM version: 1.8.0_101

Invoked command: java -jar ~/Downloads/fgbio-0.5.0.jar TrimPrimers --input Tumor-Split_2_mem.dcs.sort.bam --output Tumor-Split_2_mem.dcs.trimmed.sort.bam -r ~/Bioinformatics/genomes/Human_Genome_Sequence/human_g1k_v37.fasta --primers primer_coordinates.txt

primer coordinate file: [primer_coordinates.txt](https://github.com/fulcrumgenomics/fgbio/files/1830878/primer_coordinates.txt)

Expected result: trimmed indicated read coordinates from bam file.

Observed result: Exception in thread "main" java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce.max(TraversableOnce.scala:229)
	at scala.collection.TraversableOnce.max$(TraversableOnce.scala:227)
	at scala.collection.AbstractIterator.max(Iterator.scala:1417)
	at com.fulcrumgenomics.bam.TrimPrimers.execute(TrimPrimers.scala:113)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by tfenne** [comment]
@scottrk2 the problem is caused by the lack of headers in your primer file.  Because there's only one row in your file, the software is (erroneously) interpreting it as a file with a header line and no data, and so is not emitting a more helpful error message.  Try the [attached file](https://github.com/fulcrumgenomics/fgbio/files/1833814/primers_with_headers.txt) instead please.

**Comment by scottrk2** [comment]
Ah, that isn't at all clear from the tool documentation. I can probably do a pull request to update that this evening.

**Comment by tfenne** [comment]
See https://github.com/fulcrumgenomics/fgbio/pull/393
