### ISSUE TITLE
FgBioMain | Info] GroupReadsByUmi failed.

### ISSUE THREAD

**Issue by LeanGreen** [fulcrumgenomics/fgbio#394]
After picard, fgbio SetMateInformation, when I use **## fgbio-0.5.1.jar GroupReadsByUmi** -s Adjacency, it broke.
Like this:
```
[2018/04/03 11:16:51 | FgBioMain | Info] Executing GroupReadsByUmi from fgbio version 0.5.1 as jbk@localhost.localdomain on JRE 1.8.0_162-b12 with snappy
[2018/04/03 11:16:51 | GroupReadsByUmi | Info] Filtering and sorting input.
[2018/04/03 11:16:51 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 0.07 minutes.
Exception in thread "main" java.lang.NullPointerException
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$8(GroupReadsByUmi.scala:457)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$8$adapted(GroupReadsByUmi.scala:457)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:502)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:500)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:465)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```
How can I solve this problem?

**Comment by nh13** [comment]
Can you confirm your reads have the `RX` tag present, or the custom tag if you specified the raw-tag with `--raw-tag`?  I'd bet a $1 the `RX` tag is missing from one of your reads.  On the other hand, the tool should do a better job of providing an error message (it was supposed to); I have a fix here: https://github.com/fulcrumgenomics/fgbio/pull/406
