### ISSUE TITLE
Regression: CallMolecularConsensusReads

### ISSUE THREAD

**Issue by KjellSwedin** [fulcrumgenomics/fgbio#400]
Hi,

I'm seeing different behavior between 0.4 and 0.6. Under 0.4 my call to CallMolecularConsensusReads succeeds. Under 0.6 it fails with a "not sorted" error. The call to sort then fails as well. Here is what I am seeing -- any advice appreciated:

singularity exec java8.img java -jar /home/local/AMC/kjells/smmips/bin//fgbio/fgbio-0.4.0.jar CallMolecularConsensusReads --input=results_scons/NPM1_ins_170837526_forward.cc2_sam --output=results_scons/NPM1_ins_170837526_forward.cc3.sam --error-rate-post-umi=30 --min-reads=2 --min-input-base-quality 20
[2018/04/23 23:25:40 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 0.4.0 as kjells@larf on JRE 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12 with snappy
[2018/04/23 23:25:42 | CallMolecularConsensusReads | Info] Total Raw Reads Considered: 1,808.
[2018/04/23 23:25:42 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Orphan Consensus Created: 0 (0.0000).
[2018/04/23 23:25:42 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Mismatching Cigars: 5 (0.0028).
[2018/04/23 23:25:42 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Insufficient Support: 3 (0.0017).
[2018/04/23 23:25:42 | CallMolecularConsensusReads | Info] Consensus reads emitted: 706.
[2018/04/23 23:25:42 | FgBioMain | Info] CallMolecularConsensusReads completed. Elapsed time: 0.10 minutes.
scons: done building targets.
kjells@larf:~/smmips$ scons

singularity exec java8.img java -jar /home/local/AMC/kjells/smmips/bin//fgbio/fgbio-0.6.0.jar CallMolecularConsensusReads --input=results_scons/NPM1_ins_170837526_forward.cc2_sam --output=results_scons/NPM1_ins_170837526_forward.cc3.sam --error-rate-post-umi=30 --min-reads=2 --min-input-base-quality 20
[2018/04/23 23:26:49 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 0.6.0 as kjells@larf on JRE 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12 with snappy
[2018/04/23 23:26:49 | FgBioMain | Fatal] ##################################################################################################################################################################
[2018/04/23 23:26:49 | FgBioMain | Fatal] Execution failed!
[2018/04/23 23:26:49 | FgBioMain | Fatal] File /home/local/AMC/kjells/smmips/results_scons/NPM1_ins_170837526_forward.cc2_sam is not sorted correctly. Please sort with fgbio SortBam -s TemplateCoordinate.
[2018/04/23 23:26:49 | FgBioMain | Fatal] ##################################################################################################################################################################
[2018/04/23 23:26:49 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 0.06 minutes.
scons: *** [results_scons/NPM1_ins_170837526_forward.cc3.sam] Error 1
scons: building terminated because of errors.

singularity exec java8.img java -jar /home/local/AMC/kjells/smmips/bin//fgbio/fgbio-0.6.0.jar SortBam -s TemplateCoordinate  --input=results_scons/NPM1_ins_170837526_forward.cc2_sam --output=results_scons/NPM1_ins_170837526_forward.cc2_sorted.sam
[2018/04/23 23:35:39 | FgBioMain | Info] Executing SortBam from fgbio version 0.6.0 as kjells@larf on JRE 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12 with snappy
[2018/04/23 23:35:39 | FgBioMain | Info] SortBam failed. Elapsed time: 0.05 minutes.
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:890)
at htsjdk.samtools.SAMRecord.getMateUnmappedFlag(SAMRecord.java:917)
at com.fulcrumgenomics.bam.api.SamRecord.mateUnmapped(SamRecord.scala:98)
at com.fulcrumgenomics.bam.api.SamRecord.mateUnmapped$(SamRecord.scala:98)
at com.fulcrumgenomics.bam.api.SamRecord$EnhancedSamRecord.mateUnmapped(SamRecord.scala:262)
at com.fulcrumgenomics.bam.api.SamOrder$TemplateCoordinate$.$anonfun$sortkey$5(SamOrder.scala:167)
at com.fulcrumgenomics.util.Sorter.write(Sorter.scala:181)
at com.fulcrumgenomics.Writer.$plus$eq(Writer.scala:41)
at com.fulcrumgenomics.Writer.$plus$eq$(Writer.scala:40)
at com.fulcrumgenomics.util.Sorter.$plus$eq(Sorter.scala:78)
at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:113)
at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:101)
at com.fulcrumgenomics.Writer.$anonfun$write$1(Writer.scala:37)
at com.fulcrumgenomics.Writer.$anonfun$write$1$adapted(Writer.scala:37)
at scala.collection.Iterator.foreach(Iterator.scala:929)
at scala.collection.Iterator.foreach$(Iterator.scala:929)
at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.foreach(BetterBufferedIterator.scala:39)
at scala.collection.IterableLike.foreach(IterableLike.scala:71)
at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
at com.fulcrumgenomics.bam.api.SamSource.foreach(SamSource.scala:81)
at com.fulcrumgenomics.Writer.write(Writer.scala:37)
at com.fulcrumgenomics.Writer.write$(Writer.scala:37)
at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:101)
at com.fulcrumgenomics.Writer.$plus$plus$eq(Writer.scala:47)
at com.fulcrumgenomics.Writer.$plus$plus$eq$(Writer.scala:46)
at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:101)
at com.fulcrumgenomics.bam.SortBam.execute(SortBam.scala:68)
at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by nh13** [comment]
@KjellSwedin check out the release notes for 0.5.1, where we improve some error handling of the data.  You should be able to re-sort your input data with the `SortBam` command using the `-s TemplateCoordinate` option.  Let me know how that goes.

**Comment by nh13** [comment]
Feel free to re-open if you are still having issues.

**Comment by kpj** [comment]
@nh13: I still experience this problem with version `0.8.0`.
See below:
```bash
$ fgbio CallMolecularConsensusReads --input test.bam --output consensus.bam --min-reads=1
[..]
[2019/03/27 19:43:38 | FgBioMain | Fatal] File test.bam is not sorted correctly. Please sort with fgbio SortBam -s TemplateCoordinate.
[..]
```
Sorting however also fails:
```bash
$ fgbio SortBam -s TemplateCoordinate --input test.bam --output sorted.bam
[..]
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
	at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:901)
	at htsjdk.samtools.SAMRecord.getMateUnmappedFlag(SAMRecord.java:928)
	at com.fulcrumgenomics.bam.api.SamRecord.mateUnmapped(SamRecord.scala:99)
	at com.fulcrumgenomics.bam.api.SamRecord.mateUnmapped$(SamRecord.scala:99)
[..]
```

Does this mean that one can only call consensus sequences using paired reads?

**Comment by nh13** [comment]
@kpj did you run `GroupReadsByUmi` before `CallMolecularConsensusReads`?  Or how did you generate `test.bam`?  

Yes, at the moment, it looks like single-end reads are not supported.   Unfortunately, we do not currently have plans to support single-end reads.

**Comment by kpj** [comment]
I did not run `GroupReadsByUmi`. Instead, I am using the bam file I get from the [Broad Institute's DropSeq-Pipeline](https://github.com/broadinstitute/Drop-seq).
I thus have single-end reads, where each one is tagged with its barcode and corresponding UMI.

It seems like I won't be able to use `fgbio` then 😕(?)
Do you have a recommendation regarding a tool that calls consensus sequences (using UMIs) on single-end data?

**Comment by nh13** [comment]
I am sorry I don’t have a recommendation at this time.
