### ISSUE TITLE
GroupReadsByUmi fails due to too many open files

### ISSUE THREAD

**Issue by maribuon** [fulcrumgenomics/fgbio#403]
Hi!

I have been using FGBIO to process some targeted sequencing data with UMIs. Some of my samples are very large (~90Gb). For those, I have had a problem with GroupReadsByUmi. The error seems to indicate that there are too many open files. I have set the maximum number of open files to 95440 using ulimit -u. When the program crashes I can see ~ 100 files in the temp dir. So I don't understand what the problem is. The exact error is below. Could you please guide me on how to solve this issue? 

[2018/04/26 14:46:44 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 251.98 minutes.
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: /home/regmmbp/Scratch/tmpDir/sortingcollection.5106996803366459364.tmp (Too many open files)
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.<init>(SortingCollection.java:463)
        at htsjdk.samtools.util.SortingCollection$MergingIterator.<init>(SortingCollection.java:402)
        at htsjdk.samtools.util.SortingCollection.iterator(SortingCollection.java:272)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:451)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.io.FileNotFoundException: /home/regmmbp/Scratch/tmpDir/sortingcollection.5106996803366459364.tmp (Too many open files)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.<init>(SortingCollection.java:457)
        ... 7 more

Kind regards,
Mariana

**Comment by nh13** [comment]
@maribuon could you post the output of `ulimit -a`?  There are a number of places in the system that control the maximum # of open files.  I'd refer you to your internal IT help if I don't see anything egregious with the output of `ulimit -a`.

The next thing you could try is to pre-sort your data for input to `GroupReadsByUmi` using `SortBam`:
```
fgbio SortBam -i <in.bam> -o <out.bam> -s TemplateCoordinate -m <max-records-in-ram>
```
The key here is to increase the value of `-m` (default `1,000,000`, so larger) and give the the tool enough memory (ex. `java -Xmx8G -jar ...`) so it doesn't run out of memory.  Unfortunately, you/we would need to then modify `GroupReadsByUmi` to not sort the input since it is already sorted.  I'd be willing to make that modification if you confirm that you are able to successfully sort your data.

The other conceptual approach is to split the data by genomic position.  Perhaps start by chromosome, but you _could_ split into finer grained buckets, but realize that the `TemplateCoordinate` sort order that `GroupReadsByUmi` uses sorts by the 5' _unclipped_ position, so using alignment start positions isn't exactly correct.  I think this is too messy unless you are implementing the method for production scale.

I am sorry I don't have an easier solution for you, let me know what you think.  Perhaps @tfenne may have a suggestion or two too.

**Comment by maribuon** [comment]
Hi @nh13 !

Thank you for your answer. I had previously contacted my internal IT and their response was "That sounds like a bug in Samtools - i.e. they are opening files and not closing them. Setting ulimit appropriately to a very large number should help but really this needs to be reported to the Samtools developers..." Then I decided to contact you. The output of ulimit -a is below.

I am trying to sort the files as you suggested. I am calling it using:
$ java -Xmx64g -Djava.io.tmpdir=$tmpDir -jar $FGBIO SortBam -i --input=$intermDir/${seqID}_mapped.bam -o --input=$intermDir/${seqID}_mapped_sorted.bam -s TemplateCoordinate -m 1000000

I will let you know if the files have been sorted successfully.

Again, thank you for the support!

Kind regards,
Mariana

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 95440
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
