### ISSUE TITLE
Cannot read a SAM/BAM from stdin

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#404]
Looks like htsjdk has regressed and no longer handles `Path`s when it is `/dev/stdin`!
https://github.com/samtools/htsjdk/issues/1084

Related issues:
https://github.com/samtools/htsjdk/issues/1077
https://github.com/samtools/htsjdk/issues/1083
https://github.com/samtools/htsjdk/pull/1085

```
cat /path/to/example.bam | java -jar target/scala-2.12/fgbio-0.7.0-b6e79bd-SNAPSHOT.jar SortBam -i /dev/stdin -o /tmp/tmp.bam
[2018/05/17 21:31:38 | FgBioMain | Info] Executing SortBam from fgbio version 0.7.0-b6e79bd-SNAPSHOT as nhomer@Nils on JRE 1.8.0_66-b17 with snappy
[2018/05/17 21:31:39 | FgBioMain | Info] SortBam failed. Elapsed time: 0.03 minutes.
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:420)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:209)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.next(CommonsDef.scala:156)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:43)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:52)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:52)
	at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.foreach(BetterBufferedIterator.scala:39)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at com.fulcrumgenomics.bam.api.SamSource.foreach(SamSource.scala:81)
	at com.fulcrumgenomics.Writer.write(Writer.scala:37)
	at com.fulcrumgenomics.Writer.write$(Writer.scala:37)
	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:101)
	at com.fulcrumgenomics.Writer.$plus$plus$eq(Writer.scala:47)
	at com.fulcrumgenomics.Writer.$plus$plus$eq$(Writer.scala:46)
	at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:101)
	at com.fulcrumgenomics.bam.SortBam.execute(SortBam.scala:68)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.io.IOException: Illegal seek
	at sun.nio.ch.FileChannelImpl.position0(Native Method)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:264)
	at htsjdk.samtools.seekablestream.SeekablePathStream.position(SeekablePathStream.java:68)
	at htsjdk.samtools.seekablestream.SeekablePathStream.eof(SeekablePathStream.java:58)
	at htsjdk.samtools.seekablestream.SeekableStream.available(SeekableStream.java:106)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:583)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:562)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:525)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:418)
```

**Comment by nh13** [comment]
Commit e4e415d71c4f1088a216063fb21255a6ea395317 works just fine using htsjdk 2.13.0 and fails with 2.14.3.

**Comment by nh13** [comment]
Fixed for now in https://github.com/fulcrumgenomics/fgbio/pull/405/
