### ISSUE TITLE
HapCutToVcf error

### ISSUE THREAD

**Issue by dtomas1989** [fulcrumgenomics/fgbio#410]
Hello all,

I'm trying this command:

java -jar fgbio-0.6.1.jar HapCutToVcf -v population4_filter.vcf -i output_haplotype_file -o test.vcf

In order to convert my HapCut file to vcf file, but not working:

[2018/06/22 13:11:06 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.6.1 as dtomas on JRE 1.8.0_171-b11 with snappy
[2018/06/22 13:11:06 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0,04 minutes.
Exception in thread "main" java.lang.IllegalStateException: Could not parse block line: BLOCK: offset: 9 len: 9 phased: 9 SPAN: -84 MECscore 0.00 fragments 10
	at com.fulcrumgenomics.vcf.HapCutReader.<init>(HapCutToVcf.scala:616)
	at com.fulcrumgenomics.vcf.HapCutReader$.apply(HapCutToVcf.scala:589)
	at com.fulcrumgenomics.vcf.HapCutReader$.apply(HapCutToVcf.scala:591)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.<init>(HapCutToVcf.scala:250)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:110)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

Anyone could help me?

Many thanks in advance

**Comment by nh13** [comment]
@dtomas1989 could you send me the inputs you used to create the error as well as the hapcut/hapcut2 version?  HapCut2 has changed it's output a few times, so it might be the case you're using an old version, or that fgbio has not been updated to the new version.

**Comment by nh13** [comment]
@dtomas1989 any updates?

**Comment by nh13** [comment]
@dtomas1989 could you try the fix in #481 once it gets merged?

**Comment by jrparedes** [comment]
Hello Nils,

I am using a HAPCUT1 output and the latest fgbio release, getting this error, any suggestions?:

$ java -jar ../fgbio-1.3.0.jar HapCutToVcf -v br43.unphased2.vcf -i br43.hapcut -o br43.phased.vcf

[2021/04/12 21:33:03 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 1.3.0 as jrparedes@login2 on JRE 1.8.0_275-b01 with snappy, IntelInflater, and IntelDeflater
[2021/04/12 21:33:03 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0.03 minutes.
Exception in thread "main" java.lang.NumberFormatException: For input string: "2.0 MEC00 0.00 7.00 2.00"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at scala.collection.StringOps$.toFloat$extension(StringOps.scala:916)
        at com.fulcrumgenomics.vcf.HapCut1GenotypeInfo$.apply(HapCutToVcf.scala:495)
        at com.fulcrumgenomics.vcf.GenotypeInfo$.apply(HapCutToVcf.scala:449)
        at com.fulcrumgenomics.vcf.HapCutCall$.toHapCutCall(HapCutToVcf.scala:636)
        at com.fulcrumgenomics.vcf.HapCutReader.forNextBlockCalls(HapCutToVcf.scala:766)
        at com.fulcrumgenomics.vcf.HapCutReader.advance(HapCutToVcf.scala:780)
        at com.fulcrumgenomics.vcf.HapCutReader.hasNext(HapCutToVcf.scala:725)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:318)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:299)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:299)
        at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:139)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

$head output.hapcut

BLOCK: offset: 1 len: 2 phased: 2 SPAN: 15 MECscore 0.00 fragments 24
1       0       1       BTABA00001_EOG7428W1    147     C       A       0/1:122,0,147   10,14:-51.8,-0.0,-37.0:-37.0:0.0
2       0       1       BTABA00001_EOG7428W1    162     G       A       0/1:127,0,186   10,14:-51.8,-0.0,-37.0:-37.0:0.0
********
BLOCK: offset: 10 len: 2 phased: 2 SPAN: 85 MECscore 1.00 fragments 12
10      0       1       BTABA00047_EOG79PWH0    4028    A       C       0/1:153,0,114   6,6:-22.2,-3.4,-22.2:-18.8:1.0
11      1       0       BTABA00047_EOG79PWH0    4113    G       A       0/1:74,0,158    7,5:-18.5,-3.4,-25.9:-15.1:1.0
********
BLOCK: offset: 12 len: 5 phased: 4 SPAN: 37 MECscore 439.82 fragments 574
12      0       1       BTABA00065_EOG73NT0D    61      A       G       0/1:255,0,255   174,338:-2162.5,-1464.4,-1543.5:-79.0:156.9



$ bcftools view -H br43.unphased2.vcf |head

BTABA00001_EOG7428W1    147     .       C       A       89      PASS    DP=16;VDB=0.00566701;SGB=-0.616816;RPB=0.167959;MQB=1.00775;BQB=0.167959;MQ0F=0.0625;ICB=1;HOB=0.5;AC=1;AN=2;DP4=4,0,6,0;MQ=60  GT:PL   0/1:122,0,147
BTABA00001_EOG7428W1    162     .       G       A       94      PASS    DP=17;VDB=0.0216012;SGB=-0.636426;RPB=0.640197;MQB=0.966012;BQB=0.428703;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=7,0,7,0;MQ=60       GT:PL   0/1:127,0,186
BTABA00001_EOG7428W1    1014    .       T       C       228     PASS    DP=14;VDB=0.927913;SGB=-0.686358;MQSB=0.966012;MQ0F=0;AC=2;AN=2;DP4=0,0,7,7;MQ=60       GT:PL   1/1:255,42,0
BTABA00001_EOG7428W1    1263    .       C       T       70      PASS    DP=3;VDB=0.06;SGB=-0.453602;MQSB=1;MQ0F=0;AC=2;AN=2;DP4=0,0,1,1;MQ=60   GT:PL   1/1:97,6,0
BTABA00001_EOG7428W1    1515    .       A       G       144     PASS    DP=9;VDB=0.034401;SGB=-0.636426;MQ0F=0;AC=2;AN=2;DP4=0,0,7,0;MQ=60      GT:PL   1/1:171,21,0
BTABA00021_EOG74Z428    777     .       C       T       165     PASS    DP=11;VDB=0.355905;SGB=-0.636426;RPB=1;MQB=1;MQSB=1;BQB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=1,0,6,1;MQ=60      GT:PL   0/1:200,0,13
BTABA00047_EOG79PWH0    2730    .       T       A       82      PASS    DP=6;VDB=0.0681597;SGB=-0.511536;RPB=1;MQB=1;MQSB=0.5;BQB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=1,0,1,2;MQ=55    GT:PL   0/1:116,0,28
BTABA00047_EOG79PWH0    2916    .       C       T       100     PASS    DP=4;VDB=0.779245;SGB=-0.511536;MQSB=1;MQ0F=0;AC=2;AN=2;DP4=0,0,2,1;MQ=60       GT:PL   1/1:127,9,0
BTABA00047_EOG79PWH0    3750    .       C       T       94      PASS    DP=14;VDB=0.87268;SGB=-0.556411;RPB=0.803868;MQB=0.964642;MQSB=0.950952;BQB=0.924449;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=4,3,2,2;MQ=60   GT:PL   0/1:127,0,200
BTABA00047_EOG79PWH0    4028    .       A       C       120     PASS    DP=12;VDB=0.458326;SGB=-0.590765;RPB=0.750668;MQB=0.900802;BQB=0.900802;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=3,0,5,0;MQ=60        GT:PL   0/1:153,0,114

**Comment by nh13** [comment]
@jrparedes please open a separate issue.

**Comment by jrparedes** [comment]
@nh13 Thank you Nils for the prompt reply. I did so.
