### ISSUE TITLE
Assertion error: reads out of order 

### ISSUE THREAD

**Issue by sheenams** [fulcrumgenomics/fgbio#413]
I'm running into this error with GroupReadsByUmi after using UmiAwareMarkDuplicatesWithMateCigar. I followed the steps from the closed issue #87 , but am having slightly different issues than that user. 

I've run MergeBamAlignment on the unaligned and aligned bam, to create a 'UMI-marked-bam'. Then, I can take that UMI-marked-bam straight to GroupReadsByUmi and it works. However, if I use UmiAwareMarkDuplicatesWithMateCigar first (to create a duplicate-marked-bam, duplicates only marked, not removed), it fails with the following error:

```[2018/06/30 01:06:30 | FgBioMain | Info] Executing GroupReadsByUmi from fgbio version 0.6.1 as sheenams@larf on JRE 1.8.0_171-8u171-b11-1~deb9u1-b11 with snappy
[2018/06/30 01:06:30 | GroupReadsByUmi | Info] Filtering and sorting input.
[2018/06/30 01:06:42 | GroupReadsByUmi | Info] Sorted     1,000,000 records.  Elapsed time: 00:00:12s.  Time for last 1,000,000:   12s.  Last read position: 9:21,968,715
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Sorted     2,000,000 records.  Elapsed time: 00:00:24s.  Time for last 1,000,000:   12s.  Last read position: 22:29,091,612
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Accepted 2,049,604 reads for grouping.
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Filtered out 388,430 non-PF reads.
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Filtered out 117,332 reads that were not part of a high confidence FR mapped read pair.
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Filtered out 0 reads that contained one or more Ns in their UMIs.
[2018/06/30 01:06:55 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.
[2018/06/30 01:06:56 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 0.49 minutes.
Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ MA0337:1:1107:25428:6890/2 + MA0337:1:1105:21989:24121/2
        at scala.Predef$.assert(Predef.scala:219)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16(GroupReadsByUmi.scala:486)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16$adapted(GroupReadsByUmi.scala:485)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:485)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)```

I've tried both just marking duplicates and setting REMOVE_DUPLICATES=true. 

I then tried to run ValidateSame on the 'duplicate-marked-bam' and it says:
" No errors found"

I've tried sorting by coordinate and query name, neither helped. 

I've tried RevertSam with SANITIZE=true and all the REMOVE/RESTORE options set to false (from closed issue #87) and still get this same error. Is there something obvious that I'm missing?

**Comment by madduran** [comment]
I am also having a very similar issue. ValidateSamFile found no errors and RevertSam with SANITIZE=true did not help with the assertion error.

**Comment by nh13** [comment]
@sheenams I see the trailing `/2` on the read name which makes me suspicious.  Could you verify that the reads from the same template (R1 and R2) have the same read name.  If you see `MA0337:1:1107:25428:6890/1` and `MA0337:1:1107:25428:6890/2`, the trailing slashes need to be removed, as read names for reads from the same template/pair need to be exactly the same.  You can also post the result of `samtools view <in.bam> | grep MA0337:1:1107:25428:6890` and I can take a look.

@madduran could you check the read names too?

**Comment by sheenams** [comment]
@nh13 The slashes don't appear when I look at the bam:
```
samtools view output/165R05_E01_MONCv1_MA0337/165R05_E01_MONCv1_MA0337.dedup.bam | grep MA0337:1:1107:25428:6890
MA0337:1:1107:25428:6890        83      1       156843474       60      101M    =       156843467       -108    CATCCCCTTCTCTGTGGATGGGCAGCCGGCACCGTCTCTGCGCTGGCTCTTCAATGGCTCCGTGCTCAATGAGACCAGCTTCATCTTCACTGAGTTCCTGG  CGGCGHFG?F313GBAHGHHHGEGGEEEE?1?GHHHCEEE0GHGHFGGGGBHGHG2E2EE?G3GBFBFHGHHFG4HGHGGGDGF5FGGFFFFFFCA3AAAA  MC:Z:92M        MD:Z:101        RG:Z:165R05_E01_MONCv1_MA0337   MI:Z:CCCCCCCCC  NM:i:0MQ:i:60  UQ:i:0  AS:i:101        QX:Z:55BAEEGGA  RX:Z:CCCCCCCCC
```

**Comment by sheenams** [comment]
@nh13  Actually, that turns out to not be the issue. Running a different dataset gives the same error, but both reads are present in the output bam. Any further ideas for troubleshooting this?

```
Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ MA0337:1:1110:6261:12951/1 + MA0337:1:1112:4058:11036/1 

 samtools view output/165R08_H01_MONCv1_NA12878_MA0337/165R08_H01_MONCv1_NA12878_MA0337.dedup.bam |grep MA0337:1:1110:6261:12951
MA0337:1:1110:6261:12951        163     1       115256289       60      92M     =       115256411       223     ATTTCAAACAACCTAAAACCAACTCTTCCCATAATTAAAAAGCTCTATCTTCCCTAGTGTGGTCACCTCATTTCCCCATAAAGATTCAGAAC    11>11B33BCAAAGGGF1G1F0B01F11GFFG0BF2D1DGAAFBA112DFGHFHE10DDA1/B12BE1FAF2BAEFGGBBA1AFAGBF2FGH    MC:Z:101M       MD:Z:2G60A28    RG:Z:165R08_H01_MONCv1_NA12878_MA0337   MI:Z:TAGGTAGGG  NM:i:2  MQ:i:60 UQ:i:45 AS:i:84 QX:Z:DF31GF111  RX:Z:TAGGTAGGG
MA0337:1:1110:6261:12951        1107    1       115256411       60      101M    =       115256289       -223    CTCCTAGTACCTGTAGAGGTTAATATCCGCAAATGACTTGCTATTATTGATGGCAAATGCACAGAGGAAGCCTTCGCCTGTGCTCATGTATTGGTCTCTCA   CFB12GF@@0B1F1B011HHG2D?EECEEFGFF2BGFF1F2FHHGDFAG1B1222FDA12D1DD110FGF000AEF00F1B1B1E3BGAFAFAFAFAAAAA   MC:Z:92M        MD:Z:58A22C19   RG:Z:165R08_H01_MONCv1_NA12878_MA0337   MI:Z:TAGGCAGGG  NM:i:2  MQ:i:60 UQ:i:32 AS:i:91 QX:Z:DF31GF111  RX:Z:TAGGTAGGG

samtools view output/165R08_H01_MONCv1_NA12878_MA0337/165R08_H01_MONCv1_NA12878_MA0337.dedup.bam |grep MA0337:1:1112:4058:11036
MA0337:1:1112:4058:11036        1187    1       115256289       60      92M     =       115256411       223     ATTTCAAACAACCTAAAACCAACTCTTCCCATAATTAAAAAGCTCTATCTTCCCTAGTGCGGTAACCTCCCTTCCCCATAAAGATTCAGAAC    AAA1133DFFAAC111BAA110001FGG1BBF0ADF2AAFD0B1A11D21D21AAB0AF1AAE/CFGGF//0BFC000B01@DFHH2B2FG0    MC:Z:101M       MD:Z:2G56T9A0T21        RG:Z:165R08_H01_MONCv1_NA12878_MA0337   MI:Z:TAGGTAGGG  NM:i:4  MQ:i:60 UQ:i:76 AS:i:74 QX:Z:3DFB11A1E  RX:Z:TAGGCAGGG
MA0337:1:1112:4058:11036        83      1       115256411       60      101M    =       115256289       -223    CTCCTAGTACCTGTAGAGGTTAATATCCGCAAATGACTTGCTATTATTGATGGCAAATACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCA   FGCF@1BF@0EGGF1FE1FFD@@EEEEEEA2EFHHGGBHE2HBGF1GFGBAB222FHGHFFF1GF1EFGA?EECEFAAA11F1GE3GFGBAFAC>111>1A   MC:Z:92M        MD:Z:101        RG:Z:165R08_H01_MONCv1_NA12878_MA0337   MI:Z:TAGGCAGGG  NM:i:0  MQ:i:60 UQ:i:0  AS:i:101        QX:Z:3DFB11A1E  RX:Z:TAGGCAGGG```

**Comment by nh13** [comment]
@sheenams can you post your command line.  I bet $1 that you are using `--raw-tag MI` rather than `--raw-tag RX`  Notice that the `RX` tags are the same across reads in a pair, while `MI` is not.  `GroupReadsByUmi` writes the `MI` tag, so I am not sure what other program wrote `MI`.

**Comment by sheenams** [comment]
This is how I'm calling fgbio
`java -Xmx4g -jar /opt/fgbio-0.6.1.jar GroupReadsByUmi --input=dedup.bam  --output=grpumi.bam --strategy=adjacency --edits=1 --family-size-histogram=grpumi.histogram`

I tried adding "--raw-tag=RX" to the above fgbio call, same error. 

It looks like picard is filling in the MI tag (they have this option: ASSIGNED_UMI_TAG=MI and their docs say "Tag name to use for assigned UMI  Default value: MI " ) The MI tag isn't present in the bam I feed into picard, but is there in the bam they output.

**Comment by sheenams** [comment]
If I force UmiAwareMarkDuplicatesWithMateCigar to write to a different tag (I chose MX, since MI and RX are used), then GroupReadsByUmi works (both with and without the "--raw-tag=RX".) Thanks for your help troubleshooting this!

**Comment by leila0210** [comment]
This is how I'm calling fgbio: 
java -Xmx80G -jar /opt/local/src/fgbio/fgbio.jar GroupReadsByUmi --input=sample.unassembled.UMI.sort.bam --output=sample.unassembled.UMI.group.bam --strategy=adjacency --edits=2 --min-map-q=20 --raw-tag=RX

Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ E00591:314:H7LFNCCX2:2:1116:23622:11611/1 + **E00591:314:H7LFNCCX2:2:1111:20375:67937**/1
	at scala.Predef$.assert(Predef.scala:219)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$17(GroupReadsByUmi.scala:486)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$17$adapted(GroupReadsByUmi.scala:485)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:485)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**samtools view sample.unassembled.UMI.sort.bam | grep -n E00591:314:H7LFNCCX2:2:1111:20375:67937**
99:E00591:314:H7LFNCCX2:2:1111:20375:67937	113	chr1	967102	60	2S100M27S	=	967207	126	GCGCCAGCCCGTACCTGGGGCTCCCCCACCCCTCCCACATTGTGGTACCTGTCCTCCTCCTGCAGAGCCCGCCCAGAGATCCCATGGCTGAAGGTGGTGGCAACAGACGGGCACACACTACTTGAAGCA	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFI<IIFIIIIIIIFIIIIIAIFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFIIIIIIII<IIIIIIIIIIIIFIII	NM:i:0	MD:Z:100	MC:Z:7S120M	AS:i:100	XS:i:20	RX:Z:CTACAAGCCCGG	MQ:i:60
100:E00591:314:H7LFNCCX2:2:1111:20375:67937	177	chr1	967207	60	7S120M	=	967102	-126	CCAGGTACGGGCTGGCGCGTGACCTGGTAGCACGGCCTGGGTTTGACCCTGGCACTGCCCCTGGGACTCAGAGCTGGGAGGTGAGAAATGGGGAATGCATGTGAACCACCTGCCTCTGCACACAGCA	IIIAF7FIF-IAIIIFIIIIIIIIIIIFIIIIIIIIAIIII<IIIIIIIIIIIIFIIIIFIIFIIAF<IIIIIAIIIIIIIIFIIFFIFIA77FFFFI-<FI7A-IF7IIFIIIIIAFFFFFIIII<	NM:i:0	MD:Z:120	MC:Z:2S100M27S	AS:i:120	XS:i:19	RX:Z:CTACAAGCCCGG	MQ:i:60

It looks like the RX tags are the same across reads in a pair.

**Comment by nh13** [comment]
@leila0210 is this still an issue?
