### ISSUE TITLE
HapCutToVcf should allow ambiguity codes in the reference

### ISSUE THREAD

**Issue by mschatz** [fulcrumgenomics/fgbio#414]
Hi, I recently tried to run HapCutToVcf on a VCF file, but it crashes with this error about a malformed VCF file:

```
$ java -jar fgbio-0.6.1.jar HapCutToVcf -v phased_variants.pass.vcf -i empty.hap -o try.vcf.gz
[2018/07/06 00:03:28 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.6.1 as mschatz@yellowstone.cshl.edu on JRE 1.8.0_151-b12 with snappy
[2018/07/06 00:04:30 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 1.10 minutes.
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 418615: unparsable vcf record with allele W, for input source: file:///home/mschatz/try/phased_variants.pass.vcf
	at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:791)
	at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:576)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:538)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:341)
	at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:284)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:262)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:64)
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:372)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:353)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:314)
	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.next(CommonsDef.scala:156)
	at scala.collection.Iterator.toStream(Iterator.scala:1403)
	at scala.collection.Iterator.toStream$(Iterator.scala:1402)
	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.toStream(CommonsDef.scala:154)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1403)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.immutable.Stream.$anonfun$zip$1(Stream.scala:624)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.immutable.StreamIterator.$anonfun$next$1(Stream.scala:1058)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1047)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1047)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1052)
	at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:1075)
	at scala.collection.Iterator.isEmpty(Iterator.scala:374)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:374)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1417)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.hasNext(HapCutToVcf.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:243)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:113)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Looking at the VCF file, there is a 'W' to 'A' homozygous variant at this position:

```
$ sed -n '418615,418615p;418615q' phased_variants.pass.vcf
chr10	39316938	.	W	A	347.257	PASS	NS=1;DP=15;DPB=15.0;AC=2;AN=2;AF=1.0;RO=0;AO=20;PRO=0.0;PAO=0.0;QR=0;QA=180;PQR=0.0;PQA=0.0;SRF=0;SRR=0;SAF=2;SAR=3;SRP=0.0;SAP=3.44459;AB=0.333333;ABP=6.62942;RUN=1;RPP=6.91895;RPPR=0.0;RPL=1.0;RPR=4.0;EPP=3.44459;EPPR=0.0;DPRA=0.0;ODDS=16.5377;GTI=0;TYPE=snp;CIGAR=3M1X;NUMALT=2;MEANALT=2.0;LEN=1;MQM=60.0;MQMR=0.0;PAIRED=0.8;PAIREDR=0.0;technology.ILLUMINA=1.0;VCFALLELICPRIMITIVE;MUMAP_REF=31.0;MUMAP_ALT=60.0;MMD=2.08122;RESCUED=0;NOT_RESCUED=20;HAPLOCALLED=0	GT:BX:PS	1|1:,TATCTCATCAGAGGAC-1_69;TGTGGTATCCTCGCTA-1_47;CTGTTTACATGGTAAA-1_47;GACGGCTCATTAGCCA-1_69;TGCTACCAGTTGCAGG-1_69;GTTGCAATCTCCTGTG-1_65;GTCTCGTAGTGGAGTC-1_69;AGCCGACCACTTGAGT-1_69;GTTCTCGGTCACGCCA-1_69;GAGCAGAAGAATTCGA-1_69_69;CGAACTAAGGCTAAAT-1_69;ACTGTCCAGTACGTTC-1_69;CCACTGTAGCCACATT-1_69;CAGTGTACACTGTCGG-1_69_69;GCAACCGCAACGCCGT-1_69_69;TAGCCGGCAGACGAGT-1_47:38580966
```

I think this should be allowed, since it is correcting an ambiguity code that is present in the reference hg38 (this shows it as an N, but it is a 'W' in the fasta file):
http://genome.ucsc.edu/cgi-bin/das/hg38/dna?segment=chr10:39316918,39316958

The VCF file is available here:
http://labshare.cshl.edu/shares/schatzlab/www-data/encode/10x/version2/ENC-0002/phased_variants.pass.vcf

The error can be triggered with an empty hapcut file (I first hit it with a real hapcut file)
$ echo > empty.hap

Thanks!

Mike

**Comment by nh13** [comment]
Looks like it goes all the way back down to htsjdk. I’ll take a look.

**Comment by nh13** [comment]
@mschatz according to the [VCF 4.3 spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf) we have the following:

> If the reference sequence contains IUPAC ambiguity codes not allowed by this specification (such as R = A/G), the ambiguous reference base must be reduced to a concrete base by using the one that is first alphabetically (thus R as a reference base is converted to A in VCF.)

So `W` as the reference isn't spec-compliant. 

Nonetheless, see section 1.4.5, where it states: 

> Symbolic alleles can be used also to represent genuinely ambiguous data in VCF, for example:

Since the _input_ VCF (`phased_variants.pass.vcf`) is the offender, I can think a few solutions:

1. Go back to the tool that generated it and updated it to be spec-compliant (10X Genomics)?
2. Write a tool that specifically changes IUPAC reference bases to be spec-compliant.  That should be fairly trivial, let me know if you need help.
3. Change your reference by either masking (to `N`) or converting (`W` to `A`).

Let me know what your thinking.

**Comment by mschatz** [comment]
Yes, this vcf file comes from LongRanger which used freebayes for the variant calling. I wrote a one-liner in awk to address, but seemed like an unnecessary error since the reference base is indeed a 'W' (the spec seems to be unnecessarily strict in this regard). Would it be possible to add an option to convert ambiguity codes on the fly?

Thank you!

Mike
