### ISSUE TITLE
HapCutToVcf reference dictionary is required for creating Tribble indices on the fly

### ISSUE THREAD

**Issue by mschatz** [fulcrumgenomics/fgbio#415]
Im getting this error when I try to run HapCutToVCF:

```
$ java -jar fgbio-0.6.1.jar HapCutToVcf -v phased_variants.pass.vcf -i empty.hap -o try.vcf
[2018/07/06 00:12:51 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.6.1 as mschatz@yellowstone.cshl.edu on JRE 1.8.0_151-b12 with snappy
[2018/07/06 00:12:51 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0.06 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: A reference dictionary is required for creating Tribble indices on the fly
	at htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.build(VariantContextWriterBuilder.java:427)
	at com.fulcrumgenomics.vcf.HapCutToVcf.makeWriter(HapCutToVcf.scala:129)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:111)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Googling around other tools are reporting the same error, and the work around is to output a compressed vcf file (.vcf.gz)

```
$ java -jar fgbio-0.6.1.jar HapCutToVcf -v phased_variants.pass.vcf -i empty.hap -o try.vcf.gz
[2018/07/06 00:14:13 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.6.1 as mschatz@yellowstone.cshl.edu on JRE 1.8.0_151-b12 with snappy
```

This finishes in a few minutes and seems to run fine. Im getting the error with any VCF file and any hapcut file. Would be nice if this could be corrected.

Cheers,

Mike

**Comment by nh13** [comment]
I see what's happening here.  This is a frustrating feature of `htsjdk`'s support for VCFs.  In `fgbio` when creating the writer to write the output VCF, we set the option index the output on the fly (`INDEX_ON_THE_FLY`).  For a block-compressed VCF, the reference dictionary (the CONTIG lines in the VCF header) are not required.  But for either BCF or plain-VCF, a reference dictionary is required.  I am slightly surprised it wants to index a plain-VCF, but that's the frustrating feature in `htsjdk`.

I see a few options:

1. Like you did, output block-compressed VCF (`vcf.gz`) and it will run just fine and create an index.
2. Add `CONTIG` lines in your VCF.  I think this is a good idea generally, since so many times with VCF and in particular BED files, I don't know which genome assembly was used (this is why I love Picard interval lists and not BED files).
3. I could also update `HapCutToVcf` to either have a command line option to turn off indexing the output, or just always turn it off for VCF output (perhaps folks use tribble indexes for IGV, so not the best option).

Let me know your thoughts on these suggestions.

**Comment by mschatz** [comment]
It is a weird error mode to allow gzip'ed compressed but not compressed VCF files, especially since gzip is supposed to be a lossless compression format. It really threw me for a loop, especially since this used to work fine with earlier versions of htsjdk/fgbio. I dont think requiring CONTIG lines are a good solution because they are not generally included by variant callers, so I think that means turning off indexing is the best solution. If someone needs them for IGV, you can build them using igvtools on the command line or within the IGV Gui.

Thanks for looking at this!

Mike

**Comment by mschatz** [comment]
Thanks for adding the option, I think that will be the easiest and most flexible way to move forward. I dont think it is worth posting an issue -- they seem to be well aware of it, considering that Picard and other tools broke from this update: 
https://gatkforums.broadinstitute.org/gatk/discussion/6071/problem-with-picard-filtervcf

Thanks!

Mike
