### ISSUE TITLE
ReviewConsensusVariants 'List of intervals is not optimized' for consensus reads

### ISSUE THREAD

**Issue by katigans** [fulcrumgenomics/fgbio#423]
Hi there,

I am running into an issue with ReviewConsensusVariants:

    $ java -jar fgbio-0.6.1.jar ReviewConsensusVariants -i allSamples.vt.vcf -s S1 -c S1.consensus.sorted.bam -g S1.grouped.bam -r Homo_sapiens.GRCh37.fa --output S1.review
    [2018/08/09 13:22:59 | FgBioMain | Info] Executing ReviewConsensusVariants from fgbio version 0.6.1 as kglennon@albizia.genome.mcgill.ca on JRE 10.0.1+10 with snappy
    [2018/08/09 13:22:59 | ReviewConsensusVariants | Info] Loading variants from /Users/kglennon/Documents/Abacus/GenPipes1/July31_UMI/allSamples.vt.vcf
    [2018/08/09 13:23:00 | ReviewConsensusVariants | Info] Loaded 6365 variant positions for review.
    [2018/08/09 13:23:00 | ReviewConsensusVariants | Info] Extracting consensus reads from /Users/kglennon/Documents/Abacus/GenPipes1/July31_UMI/S1.consensus.sorted.bam
    [2018/08/09 13:23:00 | FgBioMain | Info] ReviewConsensusVariants failed. Elapsed time: 0.04 minutes.
    Exception in thread "main" java.lang.IllegalArgumentException: List of intervals is not optimized: 0:103353933-103353933 abuts 0:103353934-103353934
    at htsjdk.samtools.BAMFileReader.assertIntervalsOptimized(BAMFileReader.java:883)
    at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:913)
    at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
    at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
    at com.fulcrumgenomics.bam.api.SamSource.query(SamSource.scala:98)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.execute(ReviewConsensusVariants.scala:189)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
    at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
    at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

I originally thought there may be an issue with unmapped reads being in my consensus file, however I removed all unmapped reads and ran the command on only the mapped consensus reads and resulted in the same error. 

Any help would be much appreciated!

**Comment by realityjunky** [comment]
katigans, I have the same issue.

**Comment by nh13** [comment]
@katigans and @realityjunky I have just merged a fix into master for this bug.  Could you see if this solves your problem?
