### ISSUE TITLE
CollectDuplexSeqMetrics Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by ktsangaras** [fulcrumgenomics/fgbio#441]
Hi everyone 

I just started using fgbio for my UMI experiment and i am having difficulties generating the Metrics. Most likely i am doing something wrong so i would i appreciate your help to resolve the issue. 
The experiment that we run has the UMI on the P5 illumina index primer (AATGATACGGCGACCACCGAGATCTNNNNNNNNNACACTCTTTCCCTACACGACGCTCTT) after MiSeq demultiplexing we end up with 4 files (r1,r2,i1,i2 (umi)). 

We aligned the data to the hg19 using bwa mem and we generated a bam file. After that i run the following  fgbio commands:

#Annotate using fgbio to add UMIs to reads
java -jar fgbio-0.7.0-a33a970-SNAPSHOT.jar AnnotateBamWithUmis -i sample1_S1_L001_marked_h_realigned_recal.bam -f sample1_S1_L001_I2_001.fastq -o sample1_recal_annotated.bam

#filter SE, unaligned reads, and secondary alignment using FilterBam  
java -jar fgbio-0.7.0-a33a970-SNAPSHOT.jar FilterBam -i sample1_recal_annotated.bam -o sample1_recal_annotated_filter.bam -U true -P true -S true

#sort reads by queryname
 java -jar fgbio-0.7.0-a33a970-SNAPSHOT.jar SortBam -i sample1_recal_annotated_filter.bam -o sample1_recal_annotated_filter_sort_queryname.bam -s Queryname 

The last step (sort bam first few lines) file data looks as follows:
M00748:122:000000000-C5KC4:1:1101:10001:15656   113     chr11   126912872       60      74M     =       126912872       0       TTTGCGATGTCATCTGAAGGCTGACCTGGAGCTGGCTGGATCTACTTCCAAGATGGCTCATCCCATGGCTGGCA      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC      MC:Z:74M        MD:Z:74 NM:i:0  AS:i:74 XS:i:0  RX:Z:TATTTACAC
M00748:122:000000000-C5KC4:1:1101:10001:15656   177     chr11   126912872       60      74M     =       126912872       0       TTTGCGATGTCATCTGAAGGCTGACCTGGAGCTGGCTGGATCTACTTCCAAGATGGCTCATCCCATGGCTGGCA      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC      MC:Z:74M        MD:Z:74 NM:i:0  AS:i:74 XS:i:0  RX:Z:TATTTACAC
M00748:122:000000000-C5KC4:1:1101:10001:7245    65      chr5    57253401        60      75M     =       57253401        0       GTTTTTAACTGTGGTATCATTTTGTTTCAAGGAACGTGATTTGCTAAGGGAATATTCAAGTGATGCTGTGATCAA     CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     MC:Z:75M        MD:Z:75 NM:i:0  AS:i:75 XS:i:0  RX:Z:ATTTGACAC
M00748:122:000000000-C5KC4:1:1101:10001:7245    129     chr5    57253401        60      75M     =       57253401        0       GTTTTTAACTGTGGTATCATTTTGTTTCAAGGAACGTGATTTGCTAAGGGAATATTCAAGTGATGCTGTGATCAA     CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     MC:Z:75M        MD:Z:75 NM:i:0  AS:i:75 XS:i:0  RX:Z:ATTTGACAC
M00748:122:000000000-C5KC4:1:1101:10002:8431    113     chr5    20920202        12      74M     =       20920202        0       CAGAATATTTATTGCCTTCTGCACTGTTCCGCTTTCTCTTGCTGTTGCTTTGTGAATAGAAAAAAATTTGTTTT      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC      XA:Z:chr5,+34282142,74M,1;      MC:Z:74M        MD:Z:74 NM:i:0  AS:i:74 XS:i:69 RX:Z:GGCTACACT
M00748:122:000000000-C5KC4:1:1101:10002:8431    177     chr5    20920202        12      74M     =       20920202        0       CAGAATATTTATTGCCTTCTGCACTGTTCCGCTTTCTCTTGCTGTTGCTTTGTGAATAGAAAAAAATTTGTTTT      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC      XA:Z:chr5,+34282142,74M,1;      MC:Z:74M        MD:Z:74 NM:i:0  AS:i:74 XS:i:69 RX:Z:GGCTACACT
M00748:122:000000000-C5KC4:1:1101:10003:13798   113     chr3    63823553        60      75M     =       63823553        0       TGATTCAGGCTGCAGATTTTACCTCACAACATTAAAAACTGCATGAAAACTGTAGTCAGTAATAATGTATTTGCA     GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC     MC:Z:75M        MD:Z:75 NM:i:0  AS:i:75 XS:i:19 RX:Z:TAGACACAC

I then tried to run the collect duplex metrics using the following command:
java -jar fgbio-0.7.0-a33a970-SNAPSHOT.jar CollectDuplexSeqMetrics -i sample1_recal_annotated_filter_sort_queryname.bam -o test1 -u true

and i keep getting the following error:

[2018/10/29 09:45:49 | FgBioMain | Info] CollectDuplexSeqMetrics failed. Elapsed time: 0.04 minutes.
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:47)
	at scala.collection.immutable.StringOps.length(StringOps.scala:47)
	at scala.collection.IndexedSeqOptimized.segmentLength(IndexedSeqOptimized.scala:192)
	at scala.collection.IndexedSeqOptimized.segmentLength$(IndexedSeqOptimized.scala:191)
	at scala.collection.immutable.StringOps.segmentLength(StringOps.scala:29)
	at scala.collection.GenSeqLike.prefixLength(GenSeqLike.scala:94)
	at scala.collection.GenSeqLike.prefixLength$(GenSeqLike.scala:94)
	at scala.collection.immutable.StringOps.prefixLength(StringOps.scala:29)
	at scala.collection.IndexedSeqOptimized.takeWhile(IndexedSeqOptimized.scala:152)
	at scala.collection.IndexedSeqOptimized.takeWhile$(IndexedSeqOptimized.scala:152)
	at scala.collection.immutable.StringOps.takeWhile(StringOps.scala:29)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$collect$4(CollectDuplexSeqMetrics.scala:354)
	at scala.collection.TraversableLike.$anonfun$groupBy$1(TraversableLike.scala:321)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.groupBy(TraversableLike.scala:320)
	at scala.collection.TraversableLike.groupBy$(TraversableLike.scala:318)
	at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$collect$2(CollectDuplexSeqMetrics.scala:354)
	at scala.runtime.java8.JFunction1$mcVD$sp.apply(JFunction1$mcVD$sp.java:12)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofDouble.foreach(ArrayOps.scala:275)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.collect(CollectDuplexSeqMetrics.scala:349)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.execute(CollectDuplexSeqMetrics.scala:326)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

Can you guys help? do you know what am i doing wrong?

Thank you 
k

**Comment by tfenne** [comment]
@ktsangaras There are two problems here.  The first is that `CollectDuplexSeqMetrics` clearly states in it's usage that it expects as input "exact BAM output by the GroupReadsByUmi tool (in the sort-order it was produced in)", whereas you appear to be running it on a `queryname` sorted BAM that has not had `GroupReadsByUmi` run on it.

The second is that `CollectDuplexSeqMetrics` is intended to produce metrics for _duplex_ seq libraries - i.e. libraries created in such a way that each read has a pair of UMIs and that the reads from opposite strands of the same double-stranded molecule have related UMIs.  See [this paper](https://www.ncbi.nlm.nih.gov/pubmed/25299156) for more details.  Your data appears to be single-UMI data, so this is not the tool for you.

I think what you probably want to do is to run `GroupReadsByUmi` with the `--family-size-histogram` option.  This will give you some basic information about tag family sizes that you can use to QC your library.
