### ISSUE TITLE
FastqSource doesn't support piping

### ISSUE THREAD

**Issue by gpratt** [fulcrumgenomics/fgbio#442]
Here is a minimally reproducing bit of code

```
(toxoprobeorator) [ec2-user@ip-172-31-42-170 ad-hoc]$ cat foo.fastq | java -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx4096m -jar /pipeline/packages/fgbio.jar TrimFastq -i /dev/stdin -o /dev/stdout -l 10
[2018/11/02 22:56:43 | FgBioMain | Info] Executing TrimFastq from fgbio version 0.6.1 as ec2-user@ip-172-31-42-170 on JRE 1.8.0_152-release-1056-b12 with snappy
[2018/11/02 22:56:43 | FgBioMain | Info] TrimFastq failed. Elapsed time: 0.04 minutes.
Exception in thread "main" java.io.IOException: Illegal seek
	at sun.nio.ch.FileChannelImpl.position0(Native Method)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:264)
	at sun.nio.ch.ChannelInputStream.available(ChannelInputStream.java:116)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:70)
	at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
	at scala.collection.AbstractIterator.to(Iterator.scala:1417)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1417)
	at com.fulcrumgenomics.fastq.FastqSource.fetchNextRecord(FastqSource.scala:101)
	at com.fulcrumgenomics.fastq.FastqSource.$anonfun$next$8(FastqSource.scala:94)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
	at com.fulcrumgenomics.fastq.FastqSource.next(FastqSource.scala:94)
	at com.fulcrumgenomics.fastq.TrimFastq.$anonfun$execute$3(TrimFastq.scala:62)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at com.fulcrumgenomics.fastq.TrimFastq.execute(TrimFastq.scala:62)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

I can't attach a fastq file, so here is the contents.

```
@2:3284/1
AGAGGAGCAATGGGAAAATAGTCAAACTTGGTGCCATTAAGTTAGACAAAGAGCTAAGGGGGTAACTGTTTTCTATGTCAACAATGAAGTGATTTTATTTTTAAATTCACAAATAGATAAGGGCTGTTGAAGC
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{
@2:3284/2
TTCTAAATAGTTTATGAGAGGAGGAAGGAGAAGAAGAGTGANAGAAAGATTGTTTTTTTTTTAAATTTGTCAGAAAACTAAATGAATCTCGCTGCCTAGCTTCTGTATTAGAGACACACAACTNTAAACCNT
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{{{{{#{
@2:3286/1
AGAGGAGCAATGGGAAAATAGTCAAACTTGGTGCCATTAAGTTAGACAAAGAGCTAAGGGGGTAACTGTTTTCTATGTCAACAATGAAGTGATTTTATTTTTAAATTCACAAATAGATAAGGGNTGNTNNAGCAGGN
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{#{##{{{{{{#
@2:3286/2
AGAGATATTTCTAAATAGTTTATGAGAGGAGGAAGGAGAAGAAGAGTGAGAGANAGATTGTTTTTTTTTTAAATTTNTNAGAAAACTAAATGAATCTCGNTGNNTANCNTCTGTNTTAGAGNNNNNNAACTGTAAN
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{{{{{{{{{{{{{{{{{{{{{#{#{{{{{{{{{{{{{{{{{{{{#{{##{{#{#{{{{{#{{{{{{######{{{{{{{{#
@2:3497/1
CAATGGGAAAATAGTCAAACTTGGTGCCATTAAGTTAGACAAAGAGCTAAGGGGGTAACTGTTTTCTATGTCAACAATGAAGTGATTTTATTTTTAAATTCACAAATAGATAAGGGCTGTTGAAGNAGGGTTTACA
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{{{{{{{{{
@2:3497/2
AAGGTCAGAGATATTTCTAAATAGTTTATGAGAGGAGGAAGGAGAAGAAGAGTGAGAGAAAGATTGTTTTTTTTTTAAATTTGTCAGAAAACTAAATGAATCTCGCTGCCTAGCTTCTGTATTAGAGNNACACAAC
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{##{{{{{{{
@2:3795/1
ATAGTCAAACTTGGTNCCATTAAGTTAGACAAAGAGCTAAGGGGGTAACTGTTTTCTATGTCAACAATGAAGTGATTTTATTTTTAAATTCACAAATAGATAAGGGCTGTTGAAGCAGNNTTTACAGT
+
{{{{{{{{{{{{{{{#{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{##{{{{{{{{
@2:3795/2
GAGATATTTCTAAATAGTTTATGAGAGGAGGAAGGAGAAGAAGAGTGAGAGANAGATTGTTTTTTTTTTAAATTTNTCAGAAAACTAAATGAANNNNGNTGCCTANCTNCNGTATTAGAGNNNCNNA
+
{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{#{{{{{{{{{{{{{{{{{{{{{{#{{{{{{{{{{{{{{{{{####{#{{{{{{#{{#{#{{{{{{{{{###{##{
```

**Comment by nh13** [comment]
Could this be a similhttps://github.com/samtools/htsjdk/issues/1084 and the bug reported there?

**Comment by tfenne** [comment]
So perhaps in `Io` we need to detect if the given `Path` is `Io.StdIn` and if so, just return `System.in` instead of opening a new input stream with `Files.newInputStream()`?

**Comment by nh13** [comment]
Looks like this is fixed, likely due to https://github.com/fulcrumgenomics/commons/commit/c6d541414ec0ab0bee54284dd19f932264fb6199
