### ISSUE TITLE
error on sort --sort-order=TemplateCoordinate

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [fulcrumgenomics/fgbio#465]
I have this error using fgbio version(fgbio --version Version: 0.7.0) but I'm not able to do  data:

```
[2019/02/25 22:12:06 | FgBioMain | Info] Executing SortBam from fgbio version 0.7.0 as@Tardis on JRE 1.8.0_192-b01 with snappy
[2019/02/25 22:12:06 | FgBioMain | Info] SortBam failed. Elapsed time: 0.05 minutes.
Exception in thread "main" htsjdk.samtools.SAMException: Mate CIGAR (Tag MC) not found: M02898:33:000000000-B62RL:1:1105:5312:7836 2/2 128b aligned to chr1:115251726-115251853.
	at htsjdk.samtools.SAMUtils.getMateUnclippedEnd(SAMUtils.java:887)
	at com.fulcrumgenomics.bam.api.SamOrder$TemplateCoordinate$.$anonfun$sortkey$5(SamOrder.scala:171)
	at com.fulcrumgenomics.util.Sorter.write(Sorter.scala:181)
	at com.fulcrumgenomics.Writer.$plus$eq(Writer.scala:41)
	at com.fulcrumgenomics.Writer.$plus$eq$(Writer.scala:40)
	at com.fulcrumgenomics.util.Sorter.$plus$eq(Sorter.scala:78)
	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:113)
	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:101)
	at com.fulcrumgenomics.Writer.$anonfun$write$1(Writer.scala:37)
	at com.fulcrumgenomics.Writer.$anonfun$write$1$adapted(Writer.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.foreach(BetterBufferedIterator.scala:39)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at com.fulcrumgenomics.bam.api.SamSource.foreach(SamSource.scala:81)
	at com.fulcrumgenomics.Writer.write(Writer.scala:37)
	at com.fulcrumgenomics.Writer.write$(Writer.scala:37)
	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:101)
	at com.fulcrumgenomics.Writer.$plus$plus$eq(Writer.scala:47)
	at com.fulcrumgenomics.Writer.$plus$plus$eq$(Writer.scala:46)
	at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:101)
	at com.fulcrumgenomics.bam.SortBam.execute(SortBam.scala:68)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

**Comment by nh13** [comment]
You'll need to add the mate-cigar (`MC`) tag with [`SetMateInformation`](http://fulcrumgenomics.github.io/fgbio/tools/latest/SetMateInformation.html).  Other tools that you may use upstream, like Picard's `MergeBamAlignment`, will also set the mate-cigar, as well as recent versions of `bwa mem`.
