### ISSUE TITLE
HapCutToVcf Error

### ISSUE THREAD

**Issue by psur9757** [fulcrumgenomics/fgbio#472]
When I run HapCutToVcf on my HapCut2 output I get the following error: 
```
$ module load R/3.5.2
$ module load fgbio
$ fgbio HapCutToVcf -v results/gatk/recal1_filtered_variants.vcf -i results/hapcut2/canu3_ref -o results/hapcut2/canu3_ref_fgbio.vcf
[2019/03/22 11:58:28 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.8.0 as psur9757@hpc055 on JRE 1.8.0_111-b14 with snappy
[2019/03/22 11:58:29 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0.10 minutes.
Exception in thread "main" java.lang.IllegalStateException: Did not parse 9 or 12 fields (parsed 12) in the HapCut/HapCut2 line: 15	0	1	tig00000007	178680	G	T	0/1:8,3:11:82:82,0,299	0	100.00	21.19	2
	at com.fulcrumgenomics.vcf.HapCutCall$.toHapCutCall(HapCutToVcf.scala:612)
	at com.fulcrumgenomics.vcf.HapCutReader.forNextBlockCalls(HapCutToVcf.scala:760)
	at com.fulcrumgenomics.vcf.HapCutReader.advance(HapCutToVcf.scala:774)
	at com.fulcrumgenomics.vcf.HapCutReader.hasNext(HapCutToVcf.scala:719)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:318)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:299)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:299)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:139)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Can you please help?

I am using HapCut2 version listed here: https://github.com/vibansal/HapCUT2/releases/tag/5a6f5df as recommended here: https://github.com/vibansal/HapCUT2/issues/64

hapcut2 script
```
#!/bin/bash
#PBS -P OSR
#PBS -N hapcut2
#PBS -l select=1:ncpus=4:mem=64GB
#PBS -l walltime=20:00:00
#PBS -e logs/hapcut2.err
#PBS -o logs/hapcut2.out

cd $PBS_O_WORKDIR

module load hapcut/2
module load python/3.7.2

extractHAIRS --pacbio 1 --ref ref/canu3.fa --bam results/minimap/canu3_sorted.bam --VCF results/gatk/recal1_filtered_variants.vcf --out results/hapcut2/canu3_frags

HAPCUT2 --ea 1 --fragments results/hapcut2/canu3_frags --VCF results/gatk/recal1_filtered_variants.vcf --output results/hapcut2/canu3_ref

python3.7 /usr/local/hapcut/2/utilities/prune_haplotype.py -i results/hapcut2/canu3_ref -o results/hapcut2/canu3_ref.pruned --min_mismatch_qual 30 --min_switch_qual 30
```

**Comment by nh13** [comment]
Can you attach the inputs?

**Comment by psur9757** [comment]
All the input files are here: [hapcut2.zip](https://github.com/fulcrumgenomics/fgbio/files/2994766/hapcut2.zip)

**Comment by psur9757** [comment]
Hello, I am just checking to see if you found the error. Thank you.

**Comment by nh13** [comment]
@psur9757 unfortunately I won't have time to look at this until late this week or next due to my client work.  My apologies in advance.

**Comment by marizazh** [comment]
Hi there,
I have the same problem to convert hapcut2 result to vcf file. Can you suggest something?

**Comment by marizazh** [comment]
```[2019/04/04 18:26:45 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.9.0-47540aa-SNAPSHOT as marianna@voltxn3 on JRE 1.8.0_201-b09 with snappy
[2019/04/04 18:26:46 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 0.09 minutes.
Exception in thread "main" java.lang.IllegalStateException: Did not parse 9 or 12 fields (parsed 12) in the HapCut/HapCut2 line: 3      0       1       HiC_hic_scaffold_1      3636    C       G       0/1:14,8:22:99:273,0,716        0       100.00  58.02   2
        at com.fulcrumgenomics.vcf.HapCutCall$.toHapCutCall(HapCutToVcf.scala:612)
        at com.fulcrumgenomics.vcf.HapCutReader.forNextBlockCalls(HapCutToVcf.scala:760)
        at com.fulcrumgenomics.vcf.HapCutReader.advance(HapCutToVcf.scala:774)
        at com.fulcrumgenomics.vcf.HapCutReader.hasNext(HapCutToVcf.scala:719)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:318)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.next(HapCutToVcf.scala:299)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:299)
        at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:139)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)```

**Comment by nh13** [comment]
@marizazh see the answer I gave to @psur9757.  It's on my list of things to do, but I am prioritizing some client work at the moment.  Thank-you for your understanding.

**Comment by nh13** [comment]
@marizazh @psur9757 can you try the fix in #481 once it gets merged?

**Comment by psur9757** [comment]
So I just reinstall fgbio and try again?

**Comment by nh13** [comment]
@psur9757 you'll need to install it from the latest master branch in github.
