### ISSUE TITLE
Handle closed pipe without huge traceback in `SortFastq`

### ISSUE THREAD

**Issue by jtratner** [fulcrumgenomics/fgbio#478]
Right now, if you use `fgbio SortFastq` and do not consume all of the output, it throws a huge  traceback for the broken pipe.  This makes it confusing to a user.  E.g., when I try to pipe SortFastq to bwa with a messed up command like this (because I dropped a pipe somewhere):

```
bwa mem ... hg19.fa <(fgbio -Xmx1g SortFastq -i fq1.gz -o /dev/stdout) <(fgbio -Xmx1g SortFastq -i  fq2.gz -o /dev/stdout) samtools view -
```

I see this:

```
 ++ fgbio -Xmx1g SortFastq -i  fq2.gz -o /dev/stdout
 ++ fgbio -Xmx1g SortFastq -i fq1.gz -o /dev/stdout
 mem: invalid option -- '-'
 [2019/04/09 06:15:32 | FgBioMain | Info] Executing SortFastq from fgbio version 0.8.1 as root@job-FXf3KJ00vZJ6Yxff97z4KbY0 on JRE 11.0.1+13-LTS with snappy
 [2019/04/09 06:15:32 | FgBioMain | Info] Executing SortFastq from fgbio version 0.8.1 as root@job-FXf3KJ00vZJ6Yxff97z4KbY0 on JRE 11.0.1+13-LTS with snappy
 [2019/04/09 06:16:11 | FgBioMain | Info] SortFastq failed. Elapsed time: 0.73 minutes.
 Exception in thread "main" java.io.IOException: Broken pipe
 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
 	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
 	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
 	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
 	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
 	at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
 	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
 	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
 	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:303)
 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
 	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
 	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:211)
 	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
 	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
 	at java.base/java.io.Writer.write(Writer.java:249)
 	at java.base/java.io.Writer.append(Writer.java:322)
 	at com.fulcrumgenomics.fastq.FastqWriter.write(FastqWriter.scala:53)
 	at com.fulcrumgenomics.fastq.FastqWriter.write(FastqWriter.scala:49)
 	at com.fulcrumgenomics.Writer.$anonfun$write$1(Writer.scala:37)
 	at com.fulcrumgenomics.Writer.$anonfun$write$1$adapted(Writer.scala:37)
 	at scala.collection.Iterator.foreach(Iterator.scala:941)
 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
 	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.foreach(BetterBufferedIterator.scala:39)
 	at com.fulcrumgenomics.Writer.write(Writer.scala:37)
 	at com.fulcrumgenomics.Writer.write$(Writer.scala:37)
 	at com.fulcrumgenomics.fastq.FastqWriter.write(FastqWriter.scala:49)
 	at com.fulcrumgenomics.Writer.$plus$plus$eq(Writer.scala:47)
 	at com.fulcrumgenomics.Writer.$plus$plus$eq$(Writer.scala:46)
 	at com.fulcrumgenomics.fastq.FastqWriter.$plus$plus$eq(FastqWriter.scala:49)
 	at com.fulcrumgenomics.fastq.SortFastq.execute(SortFastq.scala:86)
 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
 	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
 	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Which hides the important line:

```
 mem: invalid option -- '-'
```

The best would be to just swallow the exception completely and not print anything. Second best would be to just print a single line:

```
 Exception in thread "main" java.io.IOException: Broken pipe
```

**Comment by nh13** [comment]
@jtratner I think this is really user preference.  As a user they can be a bit verbose, but as a developer who gets the bug reports, they are invaluable, as they reduce the number of times I have to request a test file significantly.  Nonetheless, we could make it optional to reduce the length of the stack trace for when we hit pipe errors, but this as I see it requires modification of a lot of tools; I don't see a clean way to do it.

Have you tried running fgbio with `-XX:MaxJavaStackTraceDepth=1`?  This would suppress the depth of all stack traces, but may be a good work around for now.

**Comment by jtratner** [comment]
Awesome - that XX:MaxJavaStackTrace is great. I’ll try it out!

I am biased to think that just the specific “broken pipe” error should be
caught and ignored.

Agreed on keeping long tracebacks for everything else :)

**Comment by nh13** [comment]
#482
