### ISSUE TITLE
trying to run on non network computer 

### ISSUE THREAD

**Issue by rainakumar** [fulcrumgenomics/fgbio#543]
Hi I am trying to run fgbio in non network computer and I am getting following error. I think it is looking for local host and I think it is coming from your cmdline fgbiomain class when looking for DMS. I tried to built the jar by commenting out this part of the code but I am failed to build jar using sbt. 
Exception in thread "main" java.net.UnknownHostException: removed url address: removed url address : unknown error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at com.fulcrumgenomics.cmdline.FgBioMain.printStartupLines(FgBioMain.scala:175)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:142)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:119)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:83)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.net.UnknownHostException: removed url address: unknown error
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500

Is there any way you can provide the jar without host lookup so fgbio can be run on non network computer as due to security we cannot run on network computer.

**Comment by tfenne** [comment]
It's only looking up the hostname so that it can print it out.  We could probably just catch the exception and use `unknown-host` or something like that.

It's also likely you could circumvent the issue in the mean time if you had some kind of loopback network configured (i.e. the machine isn't connected to a network but the OS presents a network interface).

**Comment by rainakumar** [comment]
Thanks for quick update on this. Can you please let me know where I can find the updated jar file after adding catch exception. I can not have loopback network due to gov security settings. I tried to build the jar using sbt but it seems like it is giving ssl issues. I appreciate your help on this.

**Comment by rainakumar** [comment]
Thanks for quick update on this. Can you please let me know where I can find the updated jar file after adding catch exception. I can not have loopback network due to gov security settings. I tried to build the jar using sbt but it seems like it is giving ssl issues. I appreciate your help on this.
