### ISSUE TITLE
Memory issues with GroupReadsByUmi and consensus calling in v.1.2.0

### ISSUE THREAD

**Issue by emissiaglia** [fulcrumgenomics/fgbio#592]
Dear Tim and Nils;
I have recently installed fgbio v.1.2.0 in a Centos 7 workstation using conda (anaconda2). I have tried to perform some tests on sequencing data which I have already analyzed in a similar machine but with the fgbio v 1.1.0 (without any issues).
This the command I was using: 
`fgbio CallMolecularConsensusReads -i ${SAMPLE}_grouped.bam -o ${SAMPLE}_ssConsensus_unmapped.bam -M 1 -r ${SAMPLE}_ssConsensus_rejected.bam -m 20` 

However, after a bit I have got the following error message, which is quite similar to the error reported in a previous issue #256

`[2020/06/16 21:32:06 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 11.76 minutes.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.immutable.Vector.iterator(Vector.scala:143)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
	at com.fulcrumgenomics.umi.VanillaUmiConsensusCaller.consensusCall(VanillaUmiConsensusCaller.scala:203)
	at com.fulcrumgenomics.umi.VanillaUmiConsensusCaller.consensusFromSamRecords(VanillaUmiConsensusCaller.scala:171)
	at com.fulcrumgenomics.umi.VanillaUmiConsensusCaller.consensusSamRecordsFromSamRecords(VanillaUmiConsensusCaller.scala:141)
	at com.fulcrumgenomics.umi.UmiConsensusCaller.consensusReadsFromSamRecords(UmiConsensusCaller.scala:282)
	at com.fulcrumgenomics.umi.UmiConsensusCaller.consensusReadsFromSamRecords$(UmiConsensusCaller.scala:280)
	at com.fulcrumgenomics.umi.VanillaUmiConsensusCaller.consensusReadsFromSamRecords(VanillaUmiConsensusCaller.scala:101)
	at com.fulcrumgenomics.umi.ConsensusCallingIterator.$anonfun$iter$2(ConsensusCallingIterator.scala:63)
	at com.fulcrumgenomics.umi.ConsensusCallingIterator$$Lambda$348/947043383.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.current(Iterator.scala:562)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:566)
	at com.fulcrumgenomics.umi.ConsensusCallingIterator.hasNext(ConsensusCallingIterator.scala:104)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at com.fulcrumgenomics.umi.ConsensusCallingIterator.foreach(ConsensusCallingIterator.scala:48)
	at com.fulcrumgenomics.commons.io.Writer.write(Writer.scala:36)
	at com.fulcrumgenomics.commons.io.Writer.write$(Writer.scala:36)
	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:107)
	at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq(Writer.scala:46)
	at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq$(Writer.scala:45)
	at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:107)
	at com.fulcrumgenomics.umi.CallMolecularConsensusReads.execute(CallMolecularConsensusReads.scala:167)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)`

Thank you very much for your help

**Comment by nh13** [comment]
Can you try increasing the memory?  `fgbio -Xmx8g CallMolecularConsensusReads`?
