### ISSUE TITLE
NoSuchElementException with ReviewConsensusVariants 

### ISSUE THREAD

**Issue by agagarega** [fulcrumgenomics/fgbio#604]
I keep getting an error (appended at the end) when running the fgbio ReviewConsensusVariants command. I perform the following steps prior to execuing ReviewConsensusVariants:

    1. Create an unmapped bam from PE reads (picard FastqToSam)
    2. Downsample (picard DownsampleSam)
    3. Extract fastqs from the downsampled bam (picard SamToFastq)
    4. Align to reference (bwa mem)
    5. Merge the aligned and unaligned bams (picard MergeBamAlignment)
    6. AnnotateBamWithUMIs (fgbio)
    7. Sort the annotated bam by query name (picard)
    8. SetMateInformation (fgbio)
    9. GroupReadsByUmi (fgbio)
    10. CallMolecularConsensus (fgbio)
    11. Extract fastqs from the consensus bam (picard SamToFastq)
    12. Realign the consensus fastqs to reference (bwa mem)
    13. Merge the unaligned and aligned consensus bams (picard MergeBamAlignment)
    14. Sort the merged consensus bam by coordinate (picard)
    15. FilterConsensusReads (fgbio)
    16. Coordinate-sort (picard) and index (samtools) the filtered consensus bam and UMI-grouped bam
    17. ReviewConsensusVariants

Final note: the last command does produce a list of variant-supporting reads, but it's always truncated after the first 1-5 positions in the interval file (probably matching the first time a missing element is encountered). Any advice would be greatly appreciated. The reads that are output do make sense for the few positions that they cover in terms of variant frequencies.

THE ERROR:
Exception in thread "main" java.util.NoSuchElementException
    at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:569)
    at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:567)
    at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:567)
    at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13(ReviewConsensusVariants.scala:255)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13$adapted(ReviewConsensusVariants.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:312)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4(ReviewConsensusVariants.scala:251)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4$adapted(ReviewConsensusVariants.scala:234)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1196)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.generateDetailsFile(ReviewConsensusVariants.scala:234)
    at com.fulcrumgenomics.umi.ReviewConsensusVariants.execute(ReviewConsensusVariants.scala:204)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
    at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
    at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by nh13** [comment]
@agagarega can you share the inputs to `ReviewConsensusVariants` as well as the version and command line?

**Comment by agagarega** [comment]
Thank you for responding so promptly.

The version is 1.2.0.

The command is:
$java -jar fgbio-1.2.0.jar ReviewConsensusVariants -i target_interval_list.txt -r ref.fa -c consensus.filtered.csort.bam -g umi-grouped.csort.bam -o supporting_reads.txt

**Comment by nh13** [comment]
@agagarega can you share the input _files_?

**Comment by agagarega** [comment]
Please see attached.
[inputs.zip](https://github.com/fulcrumgenomics/fgbio/files/5074312/inputs.zip)
[outputs.zip](https://github.com/fulcrumgenomics/fgbio/files/5074315/outputs.zip)

**Comment by nh13** [comment]
@agagarega thank-you for the inputs.  To set expectations, we're working on client projects and will take a look once we have some free time.  My apologies for the delay in advance.

**Comment by agagarega** [comment]
No worries at all. Thank you!

**Comment by mmterpstra** [comment]
same question here: https://www.biostars.org/p/455031/

Also facing the same problem. Not really able to share files. Can this help...? :

```
[2021/02/19 16:13:08 | FgBioMain | Info] Executing ReviewConsensusVariants from fgbio version 1.3.0 as user@computer on JRE 1.8.0_192-b12 with snappy, IntelInflater, and IntelDeflater
[2021/02/19 16:13:08 | ReviewConsensusVariants | Info] Loading variants from path/to/01.vcf
[2021/02/19 16:13:08 | ReviewConsensusVariants | Info] Loaded 221 variant positions for review.
[2021/02/19 16:13:08 | ReviewConsensusVariants | Info] Extracting consensus reads from  path/to/06.bam
[2021/02/19 16:13:09 | ReviewConsensusVariants | Info] Extracting raw/grouped reads from  path/to/06.bam.sorted.grouped.bam
[2021/02/19 16:13:13 | ReviewConsensusVariants | Info] Generating review file.
[2021/02/19 16:13:13 | FgBioMain | Info] ReviewConsensusVariants failed. Elapsed time: 0.17 minutes.
Exception in thread "main" java.util.NoSuchElementException
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:617)
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:615)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13(ReviewConsensusVariants.scala:255)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13$adapted(ReviewConsensusVariants.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4(ReviewConsensusVariants.scala:251)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4$adapted(ReviewConsensusVariants.scala:234)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.generateDetailsFile(ReviewConsensusVariants.scala:234)
	at com.fulcrumgenomics.umi.ReviewConsensusVariants.execute(ReviewConsensusVariants.scala:204)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

probably is due to something (missing or wrong) in the bam files because I stripped the vcf files like so (single sample, no indel/mpn/other and only gt/ad fields with at least 1 ref/alt ad count ):

```
bcftools view --samples 104103-001-006 --exclude-types indels,mnps,bnd,other /scratch/umcg-mterpstra/projects/18FEB2021_editstrat1_healthycontrols_plasma//combinevariants/18FEB2021_editstrat1_healthycontrols_plasma.0001.vcf.bak)  | grep -P '^#|\t\d/\d:\d*[123456789],\d*[123456789]:'| perl -wlane '$F[9] =~ s!^(\d/\d:\d+,\d+)\S*!$1!g;$F[8] =~ s!^(GT:AD):\S*!$1!g; print join("\t",@F)' > path/to/01.vcf
```

**Comment by mmterpstra** [comment]
https://github.com/mmterpstra/pipeline-util/blob/master/src/AddFragCountsToVariantsSamtools.pl tool to annotate unique fragment counts per alt allele bit of an WIP due to skipping reassembly so don't trust indel variants (Needs samtools and vcftools).

**Comment by sarahwajid** [comment]
The exact same issue is happening to me with version 2.0.2 and ReviewConsensusVariants:
```
[2022/07/06 02:19:46 | FgBioMain | Info] Executing ReviewConsensusVariants from fgbio version 2.0.2 as user@standard-dy-medium-1 on JRE 11.0.15-internal+0-adhoc..src with snappy, IntelInflater, and IntelDeflater
[2022/07/06 02:19:46 | ReviewConsensusVariants | Info] Loading variants from test.intervalList
[2022/07/06 02:19:46 | ReviewConsensusVariants | Info] Loaded 4040 variant positions for review.
[2022/07/06 02:19:46 | ReviewConsensusVariants | Info] Extracting consensus reads from sample_consensus.clipped.bam
[2022/07/06 02:19:49 | SamWriter | Info] Wrote         50,042 records.  Elapsed time: 00:00:03s.  Time for last 50,042:    2s.  Last read position: X:1,554,709
[2022/07/06 02:19:49 | ReviewConsensusVariants | Info] Extracting raw/grouped reads from sample_grouped.sorted.bam
[2022/07/06 02:19:59 | SamWriter | Info] Wrote      2,000,000 records.  Elapsed time: 00:00:12s.  Time for last 2,000,000:    9s.  Last read position: 11:6,422,400
[2022/07/06 02:20:06 | SamWriter | Info] Wrote      4,000,000 records.  Elapsed time: 00:00:20s.  Time for last 2,000,000:    7s.  Last read position: X:1,522,063
[2022/07/06 02:20:08 | SamWriter | Info] Wrote      4,408,428 records.  Elapsed time: 00:00:21s.  Time for last 408,428:    1s.  Last read position: X:1,554,736
[2022/07/06 02:20:08 | ReviewConsensusVariants | Info] Generating review file.
[2022/07/06 02:20:29 | FgBioMain | Info] ReviewConsensusVariants failed. Elapsed time: 0.75 minutes.
Exception in thread "main" java.util.NoSuchElementException: key not found: 414990/2
        at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:635)
        at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:633)
        at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13(ReviewConsensusVariants.scala:255)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$13$adapted(ReviewConsensusVariants.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4(ReviewConsensusVariants.scala:251)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.$anonfun$generateDetailsFile$4$adapted(ReviewConsensusVariants.scala:234)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.generateDetailsFile(ReviewConsensusVariants.scala:234)
        at com.fulcrumgenomics.umi.ReviewConsensusVariants.execute(ReviewConsensusVariants.scala:204)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```
I get some marginal output that stops about a quarter of the way through my interval list. Any fixes or suggestions? Also not able to share the input files.

**Comment by nh13** [comment]
There are some inputs zipped above if someone is able to take a look.

**Comment by nh13** [comment]
@agagarega thank-you for the test case, can you see if this PR fixes it: https://github.com/fulcrumgenomics/fgbio/pull/860?

@mmterpstra @sarahwajid this likely fixes your issue too, so take a look at the explanation and let me know if the fix works for you too!

**Comment by sarahwajid** [comment]
@nh13 so this did not fix my issue unfortunately. When I pulled your latest commit and tried rerunning I now get a different error:
```
[2022/10/11 00:45:50 | FgBioMain | Info] Executing ReviewConsensusVariants from fgbio version 2.0.3-da9ecbc-SNAPSHOT as xxxxxxxx on JRE 11.0.15-internal+0-adhoc..src with snappy, IntelInflater, and IntelDeflater
...
[2022/10/11 00:46:29 | ReviewConsensusVariants | Info] Generating review file.
[2022/10/11 00:46:33 | FgBioMain | Info] ReviewConsensusVariants failed. Elapsed time: 0.52 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Variants and consensus iterator out of sync.
```

I have tried digging into this and trying to understand what's happening: 
I get partial output of the ReviewVariant text table file and it seems to fail at a variant in my input vcf file that is multiallelic and has two alt allele calls like this in the vcf:
19	8670471	.	C	A	.	multiallelic;orientation;strand_bias;weak_evidence	AS_FilterStatus=weak_evidence;AS_SB_TABLE=710,805|4,0|3,1;DP=1729;ECNT=1;GERMQ=93;MBQ=90,64;MFRL=170,247;MMQ=60,60;MPOS=8;POPAF=7.3;ROQ=1;SOR=2.82;TLOD=3.74	GT:AD:AF:DP:F1R2:F2R1:FAD:SB	0/1/0:1515,4:0.003242:1523:1414,4:0,0:1515,4:710,805,7,1
19	8670471	.	C	T	.	multiallelic;orientation;strand_bias;weak_evidence	AS_FilterStatus=strand_bias|weak_evidence;AS_SB_TABLE=710,805|4,0|3,1;DP=1729;ECNT=1;GERMQ=93;MBQ=90,90;MFRL=170,231;MMQ=60,60;MPOS=28;POPAF=7.3;ROQ=1;SOR=2.82;TLOD=3.25	GT:AD:AF:DP:F1R2:F2R1:FAD:SB	0/0/1:1515,4:0.003229:1523:1414,3:0,0:1515,4:710,805,7,1


when I removed the second allele variant there (C>T) from the input vcf file, I then get ReviewConsensusVariants to complete without error.
I guess my question now then becomes does ReviewConsensusVariants not handle multiallelic calls? or do they need to be compressed on one line vs split in two (like what happens from bcftools norm)?
Sorry if I missed this somewhere in the documentation.

**Comment by ckrushton** [comment]
I am running into the same issue as @sarahwajid where my variant caller splits multiallelic variants into two lines by default, resulting in the same error:
```Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Variants and consensus iterator out of sync.```
When I merge the two variant calls into a single entry using `bcftools norm -m +any`, ReviewConsensusVariants completes without errors.
