### ISSUE TITLE
fgbio 1.2.0:  CallDuplexConsensusReads failed

### ISSUE THREAD

**Issue by alfonso-lam** [fulcrumgenomics/fgbio#631]
Hi, 
CallDuplexConsensusReads failed and I got this error message:

/staging/gtcmolecular/bcbio/tools/bin/fgbio CallDuplexConsensusReads --input=NGS20-004645-MRD-QIAseq-082020_UMI_bwa_grouped.bam --output=NGS20-004645-MRD-QIAseq-082020_consensus_unmapped.bam  -Djava.io.tm
pdir=/mnt/gtc-fs/data2/test/validation/bcbio/tmp  --error-rate-pre-umi=45 --error-rate-post-umi=30 --min-input-base-quality=30
[2020/09/28 12:39:12 | FgBioMain | Info] Executing CallDuplexConsensusReads from fgbio version 1.2.0 as gtcadmin@compute.gtc.local on JRE 1.8.0_192-b01 with snappy, IntelInflater, and IntelDeflater
[2020/09/28 12:39:12 | FgBioMain | Info] CallDuplexConsensusReads failed. Elapsed time: 0.04 minutes.
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at com.fulcrumgenomics.umi.DuplexConsensusCaller.$anonfun$sourceMoleculeId$1(DuplexConsensusCaller.scala:168)
        at com.fulcrumgenomics.bam.api.TransientAttrs.getOrElse(SamRecord.scala:64)
        at com.fulcrumgenomics.umi.DuplexConsensusCaller.sourceMoleculeId(DuplexConsensusCaller.scala:165)
        at com.fulcrumgenomics.umi.ConsensusCallingIterator.$anonfun$iter$1(ConsensusCallingIterator.scala:62)
...

Any suggestion of how to solve it? 
Thanks
Alfonso

**Comment by nh13** [comment]
@alfonso-lam could you post or share the input grouped BAM for us to try to reproduce and debug?

**Comment by alfonso-lam** [comment]
Hi Nils,  
Thanks for the quick reply..
Sure, no problem. Where can I post it? The BAM is 3.6GB size

**Comment by nh13** [comment]
If you could send a link for us to download that'd be ideal.  Otherwise, you could try just subsetting the BAM to 10-100 reads and verify the error is still produced, then post it here.

**Comment by alfonso-lam** [comment]
Hi Nils, 
Here is a small bam with 1000 reads.  The command I use was:
fgbio CallDuplexConsensusReads --input=small.bam --output=test.bam  --error-rate-pre-umi=45 --error-rate-post-umi=30 --min-input-base-quality=30

[small.bam.gz](https://github.com/fulcrumgenomics/fgbio/files/5294383/small.bam.gz)

**Comment by nh13** [comment]
@alfonso-lam I don't think the input BAM was grouped using the `--strategy paired` which is needed for duplex sequencing data.  The MI tags are missing the trailing `/A` and `/B`.

If you have single UMI data, see CallMolecularConsensusReads
