### ISSUE TITLE
CallMolecularConsensusReads doesn't appear to support /dev/stdout as it's output file

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#64]
Not sure why since this isn't usually a problem:

```
java -Xmx4096m -jar fgbio.jar CallMolecularConsensusReads -i grouped.unsorted.bam -o /dev/stdout -r consensus.rejects.bam -t MI -P false > tmp.bam
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: /dev/stdout (Permission denied)
    at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:610)
    at htsjdk.samtools.BAMFileWriter.finish(BAMFileWriter.java:143)
    at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:219)
    at com.fulcrumgenomics.umi.CallMolecularConsensusReads.execute(CallMolecularConsensusReads.scala:134)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
    at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
    at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
    at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.io.FileNotFoundException: /dev/stdout (Permission denied)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at htsjdk.samtools.util.BlockCompressedInputStream.checkTermination(BlockCompressedInputStream.java:471)
    at htsjdk.samtools.util.BlockCompressedOutputStream.close(BlockCompressedOutputStream.java:286)
    at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
    at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:606)
    ... 7 more
```

**Comment by nh13** [comment]
Weird, it happens for me too right at the end of processing.

**Comment by nh13** [comment]
Also:
```
java -Xmx4G -jar fgbio.jar FilterBam -i grouped.bam -o /dev/stdout > tmp.bam 
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: /dev/stdout (Permission denied)
	at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:610)
	at htsjdk.samtools.BAMFileWriter.finish(BAMFileWriter.java:143)
	at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:219)
	at com.fulcrumgenomics.bam.FilterBam.execute(FilterBam.scala:95)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.io.FileNotFoundException: /dev/stdout (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at htsjdk.samtools.util.BlockCompressedInputStream.checkTermination(BlockCompressedInputStream.java:471)
	at htsjdk.samtools.util.BlockCompressedOutputStream.close(BlockCompressedOutputStream.java:286)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:606)
```

this makes me think there is something else going on (with htsjdk?)

**Comment by nh13** [comment]
Apparently it passe line 285 in:
```
        if (this.file == null || !this.file.isFile()) return;
```

**Comment by tfenne** [comment]
This appears to be working now.
