### ISSUE TITLE
bug: ClipBam incorrectly modifies NM tags and crashes when @SQ lines are missing from bam header

### ISSUE THREAD

**Issue by eboyden** [fulcrumgenomics/fgbio#748]
I already raised an issue with Picard, which is similarly affected, and Bowtie2, which is the root cause of the problem.
https://github.com/broadinstitute/picard/issues/1764
https://github.com/BenLangmead/bowtie2/issues/365

Briefly, when using a reference with contigs that are 100% N-masked, Bowtie2 apparently ignores them when building its index, and these contigs do not appear in the `@SQ` lines in the bam headers.  fgbio `ClipBam` crashes when running on such bams, with errors like
```
[2021/12/17 02:54:35 | SamWriter | Info] Wrote     12,000,000 records.  Elapsed time: 00:02:17s.  Time for last 2,000,000:   23s.  Last read position: chrX:38,401,653
[2021/12/17 02:54:49 | FgBioMain | Info] ClipBam failed. Elapsed time: 5.28 minutes.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 167010 out of bounds for length 42811
```
It doesn't always crash, depending on the particular bam - it may depend on whether it needs to look up contigs that are listed below the missing contigs.  However even when it doesn't crash it still mangles a bunch of NM and other tags.  It seems like the ClipBam logic relies on the header matching the reference, but if they do not match, ClipBam does not exit cleanly with a description of the problem.  Note that ClipBam runs cleanly on BWA-aligned bams (which are not missing any `@SQ` lines), and on Bowtie2 bams to which I manually added in the missing `@SQ` lines.

Identifying the root cause took a bit of work, so it would be nice if ClipBam (and any other affected fgbio tools) reported the header discrepancy and exited cleanly rather than attempting to run, producing bad output, and crashing.  Alternatively ClipBam could simply ignore contigs in the reference that are missing in the header, which would allow it to run cleanly - but I'm not sure if this would be "best practices" or not.  FWIW, Samtools does not seem to be affected by the missing `@SQ` lines (that I've seen so far at least), so it may be that Samtools simply ignores contigs in the reference that are not present in the header.

**Comment by nh13** [comment]
@eboyden can you please add a test case?

**Comment by eboyden** [comment]
Using the first 250k reads of a 1000g sample (SRR1518133):
```
(base)$ zcat SRR1518133_1.fastq.gz | head -1000000 | gzip > SRR1518133_1.head1M.fastq.gz
(base)$ zcat SRR1518133_2.fastq.gz | head -1000000 | gzip > SRR1518133_2.head1M.fastq.gz

(base)$ /tools/bowtie2/bowtie2-2.4.4-linux-x86_64/bowtie2 -p 8 -1 SRR1518133_1.head1M.fastq.gz -2 SRR1518133_2.head1M.fastq.gz -x /tools/bowtie2/index/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set_masked | /tools/samtools/samtools-1.14/samtools view -@ 8 -b > SRR1518133.head1M.bowtie2-2.4.4-linux-x86_64_GRCh38-noalt-hs38d1-masked.bam
250000 reads; of these:
  250000 (100.00%) were paired; of these:
    7151 (2.86%) aligned concordantly 0 times
    176204 (70.48%) aligned concordantly exactly 1 time
    66645 (26.66%) aligned concordantly >1 times
    ----
    7151 pairs aligned concordantly 0 times; of these:
      2001 (27.98%) aligned discordantly 1 time
    ----
    5150 pairs aligned 0 times concordantly or discordantly; of these:
      10300 mates make up the pairs; of these:
        4782 (46.43%) aligned 0 times
        2872 (27.88%) aligned exactly 1 time
        2646 (25.69%) aligned >1 times
99.04% overall alignment rate

(base)$ /java/jdk-17.0.1/bin/java -Xmx8g -jar /tools/fgbio/fgbio-1.4.0.jar ClipBam -a --clip-overlapping-reads -r /references/GRCh38/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set_masked.fna -i SRR1518133.head1M.bowtie2-2.4.4-linux-x86_64_GRCh38-noalt-hs38d1-masked.bam -o SRR1518133.head1M.bowtie2-2.4.4-linux-x86_64_GRCh38-noalt-hs38d1-masked.fgbio_clipbam.bam
[2021/12/17 18:02:32 | FgBioMain | Info] Executing ClipBam from fgbio version 1.4.0 as eric@speedy on JRE 17.0.1+12-LTS-39 with snappy, IntelInflater, and IntelDeflater
[2021/12/17 18:02:32 | Bams | Info] Sorting into queryname order.
[2021/12/17 18:02:33 | Bams | Info] Seen many non-increasing record positions. Printing Read-names as well.
[2021/12/17 18:02:34 | Bams | Info] processed       500,000 Queryname sorted.  Elapsed time: 00:00:01s.  Time for last 500,000:    1s.  Last read position: chr1:205,845,432.  Last read name: SRR1518133.249936
[2021/12/17 18:02:35 | ClipBam | Info] Seen many non-increasing record positions. Printing Read-names as well.
[2021/12/17 18:02:39 | ClipBam | Info] Re-sorting into coordinate order and writing output.
[2021/12/17 18:02:58 | FgBioMain | Info] ClipBam failed. Elapsed time: 0.47 minutes.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 143671 out of bounds for length 100316
	at htsjdk.samtools.util.SequenceUtil.sumQualitiesOfMismatches(SequenceUtil.java:560)
	at htsjdk.samtools.util.SequenceUtil.sumQualitiesOfMismatches(SequenceUtil.java:527)
	at com.fulcrumgenomics.bam.Bams$.regenerateNmUqMdTags(Bams.scala:344)
	at com.fulcrumgenomics.bam.ClipBam.$anonfun$execute$9(ClipBam.scala:131)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at com.fulcrumgenomics.util.Sorter.foreach(Sorter.scala:78)
	at com.fulcrumgenomics.bam.ClipBam.execute(ClipBam.scala:130)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```
I attached the abbreviated SRR1518133 fastqs.  Briefly, I created the reference by using Bedtools to mask the specified reference file with the specified bed files; this results in three contigs that are 100% N-masked.  I then used Bowtie2 (2.4.4) to create a standard index with no options.

Reference:
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz

Bed files for masking:
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_GRC_exclusions.bed
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GCA_000001405.15_GRCh38_GRC_exclusions_T2Tv2.bed

[SRR1518133_1.head1M.fastq.gz](https://github.com/fulcrumgenomics/fgbio/files/7738326/SRR1518133_1.head1M.fastq.gz)
[SRR1518133_2.head1M.fastq.gz](https://github.com/fulcrumgenomics/fgbio/files/7738328/SRR1518133_2.head1M.fastq.gz)

**Comment by nh13** [comment]
@eboyden I think this is definitely a nice to have, and will improve the user experience.  I do think it is not unreasonable to assume the input files are not malformed and have the same sequence dictionary.  But this is Bioinformatics!  Thank-you for reporting all this with such detail, and it sounds like you have a temporary solution (update the BAM's header with the proper sequence dictionary).  I'll leave this as a future improvement to implement when we have spare cycles.

**Comment by eboyden** [comment]
Sounds good; ultimately this is a Bowtie2 issue that I hope they will fix.  And perhaps a cleaner solution would be to eliminate fully N-masked contigs from the reference in the first place.  I certainly don't expect downstream tools to handle malformed headers, but it would be nice if they at least recognized them and exited with a descriptive error message.
