### ISSUE TITLE
Where to insert Picard MarkIlluminaAdapters in an fgbio workflow?

### ISSUE THREAD

**Issue by blackbeerd** [fulcrumgenomics/fgbio#821]
How do you suggest handling the potential presence of adaptor sequence in NGS data processed with your current workflow?

I am putting together an adapted version of the 2.0 fgbio release and workflow you have published and I'm wondering where in the pipeline would be best to carry out Picard's MarkIlluminaAdaptors? A small percentage of my reads often contain adaptor read-through due to short insert length. Best practices for small insert PE reads released by Broad (https://gatk.broadinstitute.org/hc/en-us/articles/360039568932--How-to-Map-and-clean-up-short-read-sequence-data-efficiently) suggests running MarkIlluminaAdaptors right after generation of an unmapped bam and prior to merging. Therefore, my initial thought was to put the MarkIlluminaAdaptors step in just after fgbio's DemuxFastqs (in which I generate uBams) and before Step 1.2 (uBam -> Mapped BAM) of your best practices pipeline (which first converts the uBam to fastq prior to BWA mem). However, Broad's documentation (linked above) points out that some tools like SamToFastq use the XT tag generated by MarkIlluminaAdaptors to handle adaptor read-through in various ways, including by adjusting base quality scores of potential adaptor sequence to 2 (# symbol) when converting uBam to fastqs. There is also the option to convert adaptor bases to "N"s, but I'm not sure which is best for fgbio. (I assume samtools fastq tool has similar options?) I am concerned that converting base quality to 2 might cause issues in the consensus calling and filtering steps later in the pipeline. Since the filtering step relies on probabilities derived from base-quality scores, might this cause the remaining "good" sequence data in reads containing bits of adaptor to be omitted as well? OR, will the min-input-base-quality filter in the CallMolecularConsensusReads step cause those bases with quality scores of "2" to simply be ignored when making consensus sequences? What about the alternative of changing the adaptor bases as "N"s (this method does not change the original base quality score) and would converting to Ns affect the FilterConsensusReads step via the max-no-call-fraction argument?

Do you have any best practices for handling adaptor sequences?

Regards,
Chris

**Comment by nh13** [comment]
@tfenne can weigh in here too, but I am not convinced that adapter _marking_ is all that impactful when you have longer  reads (2 x 75+ bp) and map with an aligner that soft-clips (i.e. `bwa mem`).  In my experience, `bwa mem` will just soft-clip the adapter reads, and that doesn't cause false variant calls later or issues with consensus calling.

You could remove the adapter sequence rather than marking it, either prior to mapping, or after using `fgbio ClipBam` to clip the portions of a read that maps beyond its mate (`--clip-bases-past-mate`, new in 2.0).  The latter isn't searching for adapters, but that's what you're reading into for short inserts and then reading past one's mate.

In the Broad/GATK workflow linked above, `picard MarkIlluminaAdapters` adds the `XT` tag at the position of the first adapter base, then `picard SamToFastq CLIPPING_ATTRIBUTE=XT CLIPPING_ACTION=2` will change the base qualities to Q2.  But then `picard MergeBamAlignment` uses `CLIP_ADAPTERS=false`, so they're not soft-clipped by this tool.  But that means it keeps whatever `bwa mem` does with those bases (typically soft-clips them).  The explanation is unsatisfying:

> Setting CLIP_ADAPTERS to false leaves reads unclipped.

It leaves reads marked with XT as-is from `bwa mem`.  So why mark adapters at all, other than masking the bases to Q2?  Perhaps it causes no variants to be called in downstream variant callers if those bases are mapped or re-assembled due to being Q2?  So why not just soft-clip them or just remove those bases entirely?

I think if I'd modify our best-practice consensus pipeline, I'd add the `fgbio ClipBam --clip-bases-past-mate` step post-alignment, and hard-clip to remove the bases and qualities all-together for input to variant calling. <-- @tfenne

**Comment by tfenne** [comment]
I would have to verify but I'm like 95% sure that the consensus callers themselves also clip reads that extend past their mates prior to consensus calling.  If that's the case perhaps we should just add an option to hard clip at that point rather than inserting `ClipBam`.  FWIW I have not run into issues with adapter sequence being aligned and leading to false variant calls, so I'd be leary to add it as a step in the "best practice" docs because we tend not to do it ourselves.

**Comment by blackbeerd** [comment]
Thanks for weighing in - it was unclear to me how the CallMolecularConsensusReads tool handles soft-clipped reads so I was trying to avoid providing them to the tool.

However, I tried running the pipeline as follows:

uBam -> picard MarkIlluminaAdapters -> SamToFastq with **CLIPPING_ATTRIBUTE=XT CLIPPING_ACTION=N** -> BWA MEM ->  FindSwitchbackReads -> ZipperBams -> GroupReadsByUmi -> CallMolecularConsensusReads -> samtools fastq -> BWA MEM -> ZipperBams -> FilterConsensusReads 

With these settings, I actually had a slight (~1%) increase in the number of consensus sequences output in the final bam when compared to the same workflow with MarkAdaptors step omitted. I haven't check the quality of those additional consensus sequences.

I will try running with fgbio ClipBam --clip-bases-past-mate as you suggest.

The current pipeline as shown above does not include ClipBam - I assumed that with the addition of consensus-call-overlapping-bases to the CallMolecularConsensusReads tool, that clipping overlapping reads with ClipBam was unnecessary. Can you clarify this?

**Comment by nh13** [comment]
For FR pairs, `CallMolecularConsensusReads` will trim back reads that extend past its mate (in 2.0), so you shouldn't need to run `ClipBam` in 2.0 for consensus callng.

**Comment by blackbeerd** [comment]
Great - thanks!

**Comment by blackbeerd** [comment]
Also, running the above pipeline on ~100 libraries and there are a couple that fail at CallMolecularConsensusReads step with the following error:

FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 1.38 minutes. 
Exception in thread "main" java.util.NoSuchElementException: None.get

There are no obvious differences in the uBams input into the pipeline and the error can occur anywhere after 10M records or 150M records processed by CallMolecularConsensusReads. (using fgbio 2.0) This has not happened with the previous version.

Have you seen this before?

**Comment by nh13** [comment]
Do you have a full stack trace?

**Comment by blackbeerd** [comment]
(This is from a different one - same issue though)
[2022/04/13 04:36:42 | SamWriter | Info] Wrote     40,000,000 records.  Elapsed time: 00:20:46s.  Time for last 2,000,000:   63s.  Last read position: */*
[2022/04/13 04:36:43 | CallMolecularConsensusReads | Info] processed   124,000,000 records.  Elapsed time: 00:20:48s.  Time for last 1,000,000:    9s.  Last read position: chr4:55,113,611.  Last read name: A00564:170:HNLY7DSXX:3:2604:24496:1892
[2022/04/13 04:36:52 | CallMolecularConsensusReads | Info] processed   125,000,000 records.  Elapsed time: 00:20:56s.  Time for last 1,000,000:    8s.  Last read position: chr4:55,125,417.  Last read name: A00564:170:HNLY7DSXX:3:1168:19560:6997
[2022/04/13 04:37:01 | CallMolecularConsensusReads | Info] processed   126,000,000 records.  Elapsed time: 00:21:06s.  Time for last 1,000,000:    9s.  Last read position: chr4:65,352,925.  Last read name: A00564:170:HNLY7DSXX:3:1549:30210:10942
[2022/04/13 04:37:10 | CallMolecularConsensusReads | Info] processed   127,000,000 records.  Elapsed time: 00:21:14s.  Time for last 1,000,000:    8s.  Last read position: chr4:65,495,707.  Last read name: A00564:170:HNLY7DSXX:3:2645:15980:12508
[2022/04/13 04:37:20 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 21.50 minutes.
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.$anonfun$next$1(ReadAndRefPosIterator.scala:97)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:71)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.FgBioDef$.yieldAndThen(FgBioDef.scala:37)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:98)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:49)
        at scala.collection.Iterator$$anon$1.next(Iterator.scala:145)
        at scala.collection.Iterator$$anon$1.head(Iterator.scala:126)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:80)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:61)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:169)
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
        at scala.collection.immutable.Vector$.from(Vector.scala:1349)
        at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.IndexedSeq$.from(Seq.scala:115)
        at scala.collection.IterableOnceOps.toIndexedSeq(IterableOnce.scala:1265)
        at scala.collection.IterableOnceOps.toIndexedSeq$(IterableOnce.scala:1265)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.toIndexedSeq(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1(ConsensusCallingIterator.scala:111)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1$adapted(ConsensusCallingIterator.scala:109)
        at scala.Option.exists(Option.scala:406)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.advance(ConsensusCallingIterator.scala:109)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.hasNext(ConsensusCallingIterator.scala:99)
        at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:208)
        at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:224)
        at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:262)
        at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at com.fulcrumgenomics.commons.async.AsyncIterator.execute(AsyncIterator.scala:61)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run(AsyncRunnable.scala:74)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run$(AsyncRunnable.scala:71)
        at com.fulcrumgenomics.commons.async.AsyncIterator.run(AsyncIterator.scala:51)
        at java.lang.Thread.run(Thread.java:748)

**Comment by nh13** [comment]
I added a debug statement that will tell you the read name that's causing the issue in this branch: https://github.com/fulcrumgenomics/fgbio/tree/nh13-debug-overlapping.  If you build and run the JAR from that, and then extract the reads with that read name, that's probably a small enough test case for me to debug with.  This is super helpful, thank-you!

**Comment by blackbeerd** [comment]
Here are two examples from different libraries including error stack and offending reads identified with your debug script. Both sets of reads have deletions. Looks like it might be related to the consensus-call-overlapping-bases feature?

example-Library1:

[2022/04/13 17:59:07 | CallMolecularConsensusReads | Info] processed    10,000,000 records.  Elapsed time: 00:01:30s.  Time for last 1,000,000:    8s.  Last read position: chr1:175,362,698.  Last read name: A00564:170:HNLY7DSXX:3:2174:23113:35790
[2022/04/13 17:59:12 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 1.63 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: R1 does not have overlapping bases: A00564:170:HNLY7DSXX:3:1642:17237:4695
        at scala.Predef$.require(Predef.scala:337)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:80)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:61)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:171)
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
        at scala.collection.immutable.Vector$.from(Vector.scala:1349)
        at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.IndexedSeq$.from(Seq.scala:115)
        at scala.collection.IterableOnceOps.toIndexedSeq(IterableOnce.scala:1265)
        at scala.collection.IterableOnceOps.toIndexedSeq$(IterableOnce.scala:1265)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.toIndexedSeq(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1(ConsensusCallingIterator.scala:111)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1$adapted(ConsensusCallingIterator.scala:109)
        at scala.Option.exists(Option.scala:406)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.advance(ConsensusCallingIterator.scala:109)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.hasNext(ConsensusCallingIterator.scala:99)
        at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:208)
        at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:224)
        at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:262)
        at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at com.fulcrumgenomics.commons.async.AsyncIterator.execute(AsyncIterator.scala:61)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run(AsyncRunnable.scala:74)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run$(AsyncRunnable.scala:71)
        at com.fulcrumgenomics.commons.async.AsyncIterator.run(AsyncIterator.scala:51)
        at java.lang.Thread.run(Thread.java:748)

Offending reads:
A00564:170:HNLY7DSXX:3:1146:15130:11913 99      chr4    77714393        60      46M24D98M       =       77714439        67      ACACCCTGGCCCTTATAGAGAGAAAAAGTACATCCACACTCTCTTTAAAAAAAAAAAAAGCCCTCCATACTTCCCCACTCCAGAGACAACAAAGCCAAAGATGAAACATTCAACCTTCTCAAAATATTCCAAGTAGTTCTATTG        FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,:,F,F:FFFFFF:FFFFFFFFFF,FFF:FFF:FFF:F:F:FFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFF:FFFFFF:FFFF:FFFFFFFFF:FF:FFFFFFFF        BC:Z:TTCT-TTCT  MC:Z:52S21M71S  MD:Z:33A12^AAAAAAAAAAAAAAAAAAAAAAAA98   RG:Z:SBRT191126_D4      MI:Z:20539133   NM:i:25 MQ:i:24 AS:i:109        XS:i:23 RX:Z:TGTC-ACGG
A00564:170:HNLY7DSXX:3:1146:15130:11913 147     chr4    77714439        24      52S21M71S       =       77714393        -67     TTTGATGTTCTAGCTCCTATCCCTGTGGTTTCCTTATCAAAACAAAAACACCAAAAAAAAAAAAAAAAAAAAATACACCCACTACTTTATTTTTTAAAATTATTTATTAAAATTCTAATCCATACAAAACACACCCCCCCCCCC        ,:,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,F,,,F,,::F,:F:F::,,,,,,,,,,,,,,,,,F,,,,,,,,,,,,,,,,F,,,,,,,,,,,,:,,,,,,F::,,,,,:,,,FFFFFFF        BC:Z:TTCT-TTCT  MC:Z:46M24D98M  MD:Z:21 RG:Z:SBRT191126_D4      MI:Z:20539133   NM:i:0  MQ:i:60 AS:i:21 XS:i:32 RX:Z:TGTC-ACGG


example-Library2:

[2022/04/13 17:59:07 | CallMolecularConsensusReads | Info] processed    10,000,000 records.  Elapsed time: 00:01:30s.  Time for last 1,000,000:    8s.  Last read position: chr1:175,362,698.  Last read name: A00564:170:HNLY7DSXX:3:2174:23113:35790
[2022/04/13 17:59:12 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 1.63 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: R1 does not have overlapping bases: A00564:170:HNLY7DSXX:3:1642:17237:4695
        at scala.Predef$.require(Predef.scala:337)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:80)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:61)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:171)
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
        at scala.collection.immutable.Vector$.from(Vector.scala:1349)
        at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.IndexedSeq$.from(Seq.scala:115)
        at scala.collection.IterableOnceOps.toIndexedSeq(IterableOnce.scala:1265)
        at scala.collection.IterableOnceOps.toIndexedSeq$(IterableOnce.scala:1265)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.toIndexedSeq(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1(ConsensusCallingIterator.scala:111)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1$adapted(ConsensusCallingIterator.scala:109)
        at scala.Option.exists(Option.scala:406)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.advance(ConsensusCallingIterator.scala:109)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.hasNext(ConsensusCallingIterator.scala:99)
        at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:208)
        at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:224)
        at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:262)
        at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
        at com.fulcrumgenomics.commons.async.AsyncIterator.execute(AsyncIterator.scala:61)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run(AsyncRunnable.scala:74)
        at com.fulcrumgenomics.commons.async.AsyncRunnable.run$(AsyncRunnable.scala:71)
        at com.fulcrumgenomics.commons.async.AsyncIterator.run(AsyncIterator.scala:51)
        at java.lang.Thread.run(Thread.java:748)

Offending reads:
A00564:170:HNLY7DSXX:3:1642:17237:4695  99      chr1    188544095       60      90M30D54M       =       188544185       114     GAACTTGGATTGTCCTTAGTAATACGTCATCAGAATTTGGAGATTCCATACATGCATAACAAATAGAAAAAACGCTTTCATTATAATAGATTTTTTTTTTTTTTTTGAGACCGAGTCTCGCTCTGTCGCCCAGGCTGGAGTGCG        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF:FF:FFFFFF:FF:FFFFFFFFFFF:FFFFFFFFFFFF        BC:Z:TAGT-TAGT  MC:Z:82S24M38S  MD:Z:90^TTTTTTTGTTTTTTTTTTTTTGTTTGTTTT9G44      RG:Z:SBRT191126_C3      MI:Z:941154     NM:i:31 MQ:i:40 AS:i:103        XS:i:54 RX:Z:CCTC-ATGC
A00564:170:HNLY7DSXX:3:1642:17237:4695  147     chr1    188544185       40      82S24M38S       =       188544095       -114    TGGGGGGTGGGGGGGGTGGTTTTTTGTTGTCTTGTGTGTTTTGTGTTTGTTTTGTTTTTTTTTTTTTTGCTGGGGCTTTTTGTTTTTTTGTTTTTTTTTTTTTGTTGGTCGACCTTTTGTTTTTTTTTTTTTTTTTCTCCCCCC        ,::,,,,,F,,:,,,F,,,:,F,,,,,,,:,,,,F,,,,,,:,,,F,:,FFF,:,:,:F,F,,,,,,,,,,,,,,,,,,,,,,,,,:F,,:,::,,,F,,,,,,,:,,,,,,,,,,,,,F,,FFFFFFFFFF:F:,,,,,,,,F        BC:Z:TAGT-TAGT  MC:Z:90M30D54M  MD:Z:24 RG:Z:SBRT191126_C3      MI:Z:941154     NM:i:0  MQ:i:60 AS:i:24 XS:i:31 RX:Z:CCTC-ATGC

**Comment by nh13** [comment]
Perfect, I’ll add it to the queue.

**Comment by blackbeerd** [comment]
I had just had to edit my last comment - first stack log was incorrect. Corrected now.

**Comment by nh13** [comment]
For the last example, it's like to do with the fact that the two reads overlap in span, but not in mapped bases, and we need to be more careful about that.  E.g. R2 starts right after the 90M in R1, then R2 maps 24M right in R1s 30D.  That's insidious, but valid, and we should handle it.

**Comment by blackbeerd** [comment]
Like I said, the majority of the other libraries completed the pipeline without issue, so this can't be that common, but as you said - it's a possibility to account for. In the mean time, I will try removing those specific reads from the bams since they don't appear to bring much value. I haven't checked if the mapping bit is gene-coding, etc. but I'm assuming it's very unlikely to be a "real" mutation.

**Comment by nh13** [comment]
@blackbeerd I was able to reproduce and fix your issue in #824 (under code review).  You're welcome to build from source to see if that fixes it on your end.

**Comment by blackbeerd** [comment]
Great - I'll give it a go! Thanks

**Comment by nh13** [comment]
@blackbeerd if you run it on the problematic samples and confirm it works, I can then merge the PR and make a release.  This is super helpful, thank-you!

**Comment by blackbeerd** [comment]
Two libraries have already completed without issue - so far it looks like it's working... I did notice a few new lines in the output (for ver 2.0 in general) that I caught my attention. Example:

[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info] processed   201,000,000 records.  Elapsed time: 00:26:21s.  Time for last 1,000,000:   10s.  Last read position: chrY:13,950,476.  Last read name: A00564:170:HNLY7DSXX:3:1309:21549:21746
09:58:29.781 WARN  IntelInflater - Zero Bytes Written : 0
[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info] Consensus calling overlapping read pairs statistics:
[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info]     0 overlapping templates
[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info]     0 corrected templates (0.00%)
[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info]     0 overlapping bases
[2022/04/15 09:58:29 | CallMolecularConsensusReads | Info]     0 corrected bases (0.00%)
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] processed   201,037,460 records.  Elapsed time: 00:26:21s.  Time for last 37,460:    0s.  Last read position: chrY_KI270740v1_random:34,198.  Last read name: A00564:170:HNLY7DSXX:3:2518:17969:11099
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Total Raw Reads Considered: 201,037,460.
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Insufficient Support: 0 (0.0000).
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Mismatching Cigars: 1,832,104 (0.0091).
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Low Base Quality: 6,769 (0.0000).
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Orphan Consensus Created: 2,867 (0.0000).
[2022/04/15 09:58:30 | CallMolecularConsensusReads | Info] Consensus reads emitted: 42,067,946.
[2022/04/15 09:58:30 | FgBioMain | Info] CallMolecularConsensusReads completed. Elapsed time: 26.42 minutes.

Specifically the lines stating "0 corrected templates (0.00%)" and "0 corrected bases (0.00%)" - Is this expected behavior? This log is from one of the problematic files but others have the same message as well (though I haven't checked all ~100).

**Comment by nh13** [comment]
Ah, that's another good observation and likely a bug (only in the logging output).  I'll make another PR to fix that too.

**Comment by nh13** [comment]
Fixed the logging issue here: https://github.com/fulcrumgenomics/fgbio/pull/825.  This PR targets and includes the changes in #824.

**Comment by nh13** [comment]
@blackbeerd thank-you for all your help, the changes above have made it into a new release: https://github.com/fulcrumgenomics/fgbio/releases/tag/2.0.1
