### ISSUE TITLE
My fgbio pipeline worked for 1.5.1 but not 2.0.0. Why?

### ISSUE THREAD

**Issue by ymcki** [fulcrumgenomics/fgbio#835]
I have a fgbio pipeline based on 1.5.1 that generates an consensus unmapped bam without errors.

time java -jar ~/bingo/fgkit/bin/picard.jar FixMateInformation I=proper.bam O=/dev/stdout | java -jar ~/bingo/fgkit/bin/fgbio-1.5.1.jar ClipBam -i /dev/stdin -o /dev/stdout -r /data/genome_reference/Homo_sapiens_assembly19.fasta -H -a | samtools view -F 12 | awk -F"\t" '{if(/^@/){print}else{split($1,a,"::umi:");split(a[2],b,"-");printf "%s\tRX:Z:%s\n",$0,b[2]}}' | samtools view -T /data/genome_reference/Homo_sapiens_assembly19.fasta -bS - | java -jar ~/bingo/fgkit/bin/fgbio-1.5.1.jar GroupReadsByUmi -s identity -e 0 -i /dev/stdin -o /dev/stdout | java -jar ~/bingo/fgkit/bin/fgbio-1.5.1.jar CallMolecularConsensusReads -i /dev/stdin -o /dev/stdout -m 12 -M 1 | samtools view -h | sed 's/^\(@RG\tID:.*\)/\1\tSM:Lib005/' | samtools view -b -o Lib005.con.ubam -

However, when I translate it to 2.0.0, it crashes at the CallMolecularConsensusReads step:

 time java -jar ~/bingo/fgkit/bin/picard.jar FixMateInformation I=proper.bam O=/dev/stdout SO=queryname | java -jar ~/bingo/fgkit/bin/fgbio-2.0.0.jar ClipBam -i /dev/stdin -o /dev/stdout -r /data/genome_reference/Homo_sapiens_assembly19.fasta -H -a | samtools view -F 12 | awk -F"\t" '{if(/^@/){print}else{split($1,a,"::umi:");split(a[2],b,"-");printf "%s\tRX:Z:%s\n",$0,b[2]}}' | samtools view -T /data/genome_reference/Homo_sapiens_assembly19.fasta -bS - | java -jar ~/bingo/fgkit/bin/fgbio-2.0.0.jar GroupReadsByUmi -s identity -e 0 -i /dev/stdin -o /dev/stdout | java -jar ~/bingo/fgkit/bin/fgbio-2.0.0.jar CallMolecularConsensusReads -i /dev/stdin -o /dev/stdout -m 12 -M 1 | samtools view -h | sed 's/^\(@RG\tID:.*\)/\1\tSM:Lib005/' | samtools view -b -o Lib005.con.ubam -

with this error: What went wrong here?

Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.$anonfun$next$1(ReadAndRefPosIterator.scala:97)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:71)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.FgBioDef$.yieldAndThen(FgBioDef.scala:37)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:98)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:49)
        at scala.collection.Iterator$$anon$1.next(Iterator.scala:145)
        at scala.collection.Iterator$$anon$1.head(Iterator.scala:126)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:80)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:61)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:169)
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
        at scala.collection.immutable.Vector$.from(Vector.scala:1349)
        at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.IndexedSeq$.from(Seq.scala:115)
        at scala.collection.IterableOnceOps.toIndexedSeq(IterableOnce.scala:1265)
        at scala.collection.IterableOnceOps.toIndexedSeq$(IterableOnce.scala:1265)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.toIndexedSeq(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1(ConsensusCallingIterator.scala:111)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1$adapted(ConsensusCallingIterator.scala:109)
        at scala.Option.exists(Option.scala:406)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.advance(ConsensusCallingIterator.scala:109)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.hasNext(ConsensusCallingIterator.scala:99)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:594)
        at com.fulcrumgenomics.umi.ConsensusCallingIterator.hasNext(ConsensusCallingIterator.scala:79)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at com.fulcrumgenomics.umi.ConsensusCallingIterator.foreach(ConsensusCallingIterator.scala:45)
        at com.fulcrumgenomics.commons.io.Writer.write(Writer.scala:36)
        at com.fulcrumgenomics.commons.io.Writer.write$(Writer.scala:36)
        at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:109)
        at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq(Writer.scala:46)
        at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq$(Writer.scala:45)
        at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:109)
        at com.fulcrumgenomics.umi.CallMolecularConsensusReads.execute(CallMolecularConsensusReads.scala:182)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
[E::bgzf_read] bgzf_read_block error -1 after 435 of 441 bytes
[main_samview] truncated file.
[2022/04/28 17:18:21 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 14.74 minutes.
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:222)
        at htsjdk.samtools.util.BlockCompressedOutputStream.writeGzipBlock(BlockCompressedOutputStream.java:444)
        at htsjdk.samtools.util.BlockCompressedOutputStream.deflateBlock(BlockCompressedOutputStream.java:408)
        at htsjdk.samtools.util.BlockCompressedOutputStream.write(BlockCompressedOutputStream.java:301)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:212)
        at htsjdk.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:194)
        at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:144)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:197)
        at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:124)
        at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:109)
        at com.fulcrumgenomics.commons.io.Writer.$plus$eq(Writer.scala:40)
        at com.fulcrumgenomics.commons.io.Writer.$plus$eq$(Writer.scala:39)
        at com.fulcrumgenomics.bam.api.SamWriter.$plus$eq(SamWriter.scala:109)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$20(GroupReadsByUmi.scala:619)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$17(GroupReadsByUmi.scala:618)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$17$adapted(GroupReadsByUmi.scala:617)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:617)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:115)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:80)
        at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
        at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
        at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
        at java.base/java.nio.channels.Channels.access$000(Channels.java:62)
        at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
        ... 23 more

**Comment by tfenne** [comment]
I think this is a known bug that was fixed in 2.0.2 - can you try that release please?

**Comment by nh13** [comment]
Previously reported here: https://github.com/fulcrumgenomics/fgbio/issues/821

Fixed here: https://github.com/fulcrumgenomics/fgbio/pull/824
