### ISSUE TITLE
"Too many open files" when running DemuxFastqs on large sequencing run

### ISSUE THREAD

**Issue by mblohmer** [fulcrumgenomics/fgbio#855]
Hi, 

DemuxFastqs is repeatedly failing with the error "Too many open files" when I try to run it on a large sequencing run . The run contains ~3 billion paired end reads with unique dual indices and UMIs from 96 samples. DemuxFastqs works well for me on smaller files (150 million reads). 
It seems like the "DemuxFastqs" part of the program can finish , but when the program is only outputting "SamWriter | Info" it fails after having written the files for 80 samples. I am running fgbio on an HPC cluster and unfortunately can't change the # of open files. 

I am running this command with fgbio2.0.2:
`java -jar -Xmx64g -Djava.io.tmpdir=${tempdir} ../java/fgbio-2.0.2.jar DemuxFastqs -i R1_001.fastq.gz I1_001.fastq.gz I2_001.fastq.gz R2_001.fastq.gz --read-structures 1S150T 8B11M 8B2S 150T1S --metadata metadata.csv --output unmapped_bams --output-type Bam -t 4`

This is my ulimit -a output: 

> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited 
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 4133857
> max locked memory       (kbytes, -l) 64
> max memory size         (kbytes, -m) 30720000
> open files                      (-n) 8192
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) unlimited
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 4133857
> virtual memory          (kbytes, -v) 529153392
> file locks                      (-x) unlimited

And this is the error log from DemuxFastqs:

`
[2022/06/13 20:17:22 | FgBioMain | Info] DemuxFastqs failed. Elapsed time: 2,778.02 minutes.
Exception in thread "main" java.nio.file.FileSystemException: /data/naxerova/martin/analysis/library_mar22/sorter.7498166800095434592.tmp: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at com.fulcrumgenomics.commons.io.IoUtil.toInputStream(Io.scala:64)
        at com.fulcrumgenomics.commons.io.IoUtil.toInputStream$(Io.scala:58)
        at com.fulcrumgenomics.util.Io.toInputStream(Io.scala:38)
        at com.fulcrumgenomics.util.Sorter.$anonfun$iterator$1(Sorter.scala:219)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at scala.collection.immutable.List.prependedAll(List.scala:156)
        at scala.collection.immutable.List$.from(List.scala:684)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.Seq$.from(Seq.scala:42)
        at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1263)
        at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1263)
        at scala.collection.AbstractIterator.toSeq(Iterator.scala:1293)
        at com.fulcrumgenomics.util.Sorter.iterator(Sorter.scala:219)
        at com.fulcrumgenomics.bam.api.SamWriter.$anonfun$close$1(SamWriter.scala:132)
        at com.fulcrumgenomics.bam.api.SamWriter.$anonfun$close$1$adapted(SamWriter.scala:130)
        at scala.Option.foreach(Option.scala:437)
        at com.fulcrumgenomics.bam.api.SamWriter.close(SamWriter.scala:130)
        at com.fulcrumgenomics.fastq.SamRecordWriter.close(DemuxFastqs.scala:581)
        at com.fulcrumgenomics.fastq.DemuxFastqs$$anon$2.$anonfun$close$1(DemuxFastqs.scala:541)
        at com.fulcrumgenomics.fastq.DemuxFastqs$$anon$2.$anonfun$close$1$adapted(DemuxFastqs.scala:541)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at com.fulcrumgenomics.fastq.DemuxFastqs$$anon$2.close(DemuxFastqs.scala:541)
        at com.fulcrumgenomics.fastq.DemuxFastqs.$anonfun$execute$11(DemuxFastqs.scala:499)
        at com.fulcrumgenomics.fastq.DemuxFastqs.$anonfun$execute$11$adapted(DemuxFastqs.scala:499)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at com.fulcrumgenomics.fastq.DemuxFastqs.execute(DemuxFastqs.scala:499)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
`

I appreciate your help with this! 

Best,
Martin

**Comment by nh13** [comment]
The issue is its trying to sort the output FASTQs, and its using temporary files when there isn’t enough space in memory. This tool was originally built to handle MiSeq runs and given the voluntary nature of supporting these tools, we have not spent time scaling this tool for larger outputs, and/or porting it to a more performant programming language (happy to with financial support). 

That being said, can you try `--sort-order unsorted`? This should skip the output sorting of your BAM, which in most cases should be fine. 

There also options we have not exposed on the command line that can limit the number of records in memory and/or the number if temporary files that could be investigated. 

You could also chunk up the FASTQs, process each chunk separately, then merge/concatenate them after. Not ideal, but could be faster given the ability to parallelize across chunks.

**Comment by mblohmer** [comment]
Running the command with  `--sort-order unsorted` worked perfectly and already reduced the running time considerably. 

Thank you so much for your help and your work on fgbio!
