### ISSUE TITLE
GroupReadsByUMI produces snappy error

### ISSUE THREAD

**Issue by WackerO** [fulcrumgenomics/fgbio#857]
Hello there,

fgbio GroupReadsByUmi is used by the SAREK nextflow pipeline which I am currently working on. While trying to fix the code, I found that the command
```
fgbio \
      --tmp-dir=/tmp/pytest_workflow_iifbh2j9/Run_UMI_test/tmp \
      GroupReadsByUmi \
      -s Adjacency \
       \
      -i test-test_L1_unsorted_tagged.bam \
      -o test-test_L1_umi-grouped.bam \
      -f test-test_L1_umi_histogram.txt
```
, when run from pytest, produces a snappy error:
```
at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
     at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
   WARNING: An illegal reflective access operation has occurred
   WARNING: Illegal reflective access by org.xerial.snappy.pure.UnsafeUtil (file:/usr/local/share/fgbio/fgbio.jar) to field java.nio.Buffer.address
   WARNING: Please consider reporting this to the maintainers of org.xerial.snappy.pure.UnsafeUtil
   WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
   WARNING: All illegal access operations will be denied in a future release
   [2022/07/12 09:31:01 | FgBioMain | Info] Executing GroupReadsByUmi from fgbio version 2.0.2 as runner@0c734d8ab1de on JRE 11.0.9.1-internal+0-adhoc..src with snappy, IntelInflater, and IntelDeflater
   [2022/07/12 09:31:01 | GroupReadsByUmi | Info] Filtering the input.
   [2022/07/12 09:31:01 | GroupReadsByUmi | Info] Sorting the input to TemplateCoordinate order.
   [2022/07/12 09:31:01 | GroupReadsByUmi | Info] Seen many non-increasing record positions. Printing Read-names as well.
   09:31:01.740 WARN  IntelInflater - Zero Bytes Written : 0
   [2022/07/12 09:31:01 | GroupReadsByUmi | Info] Sorted        15,766 records.  Elapsed time: 00:00:00s.  Time for last 15,766:    0s.  Last read position: chr22:2,967.  Last read name: 923802
   [2022/07/12 09:31:01 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 0.04 minutes.
   Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/pytest_workflow_iifbh2j9/Run_UMI_test/tmp/sorter.18217100940925636068.tmp
     at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
     at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
     at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
     at java.base/java.nio.file.Files.createFile(Files.java:647)
     at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
     at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
     at java.base/java.nio.file.Files.createTempFile(Files.java:867)
     at com.fulcrumgenomics.commons.io.IoUtil.makeTempFile(Io.scala:105)
     at com.fulcrumgenomics.commons.io.IoUtil.makeTempFile$(Io.scala:104)
     at com.fulcrumgenomics.util.Io.makeTempFile(Io.scala:54)
     at com.fulcrumgenomics.util.Sorter.spill(Sorter.scala:196)
     at com.fulcrumgenomics.util.Sorter.iterator(Sorter.scala:218)
     at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:597)
     at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
     at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
     at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
     at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```
You can also find the command and error [here](https://github.com/nf-core/sarek/runs/7298883423?check_suite_focus=true) under "Output log on failure". I was able to reproduce it on a centos linux 7 machine by running the command `pytest --tag umi --symlink --kwdof --git-aware --color=yes`. Weirdly, just calling the pipeline directly (`nextflow run [main.nf](http://main.nf/) -profile test,umi,docker`) worked for me just fine, but a colleague was able to reproduce the error with both commands.

Has someone else experienced such an error by any chance? Any idea how to fix it?

**Comment by WackerO** [comment]
The error was found, it was because of a tmpdir declaration that for some reason was accepted by nextflow but not pytest. Closing this.
