### ISSUE TITLE
Error in CallMolecularConsensusReads

### ISSUE THREAD

**Issue by bebelya** [fulcrumgenomics/fgbio#861]
Hi, 

First of all, thanks a lot for a great tool! 

Is there a way to modify CallMolecularConsensusReads to prevent a crash in the following situation? 

Occasionally, a dataset has a high number of PCR duplicates. These generally manifest as reads mapping to the same position and having identical UMI. On my machine, fgbio CallMolecularConsensusReads crashes in the presence of ~10K UMI's at a position. Is it possible for CallMolecularConsensusReads  to stop accruing PCR duplicates after the first, say, 1000 sequences, when calculating a consensus? I can certainly write a script to search for overrepresented UMI's, but I was wondering if this may be easier done within CallMolecularConsensusReads? 

Ideally, the 1000 number would be a user-defined parameter depending on the available memory.

Is there a a better solution perhaps?

Thanks!

Code: 

$ fgbio GroupReadsByUmi -i $inFile -o $outFile --strategy=adjacency --edits=1 --assign-tag=MI
(this executes OK)

$ fgbio CallMolecularConsensusReads -i $inFile -o $outFile --min-reads=1 --threads=4
This crashes with the following message:

[2022/07/20 02:43:32 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 2.0.2 as xxx@yyy.com on JRE 1.8.0_332-b09 with snappy, IntelInflater, and IntelDeflater
[2022/07/20 02:43:33 | CallMolecularConsensusReads | Info] Seen many non-increasing record positions. Printing Read-names as well.
[2022/07/20 02:43:49 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 0.32 minutes.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.Iterator.concat(Iterator.scala:618)
	at scala.collection.Iterator.concat$(Iterator.scala:618)
	at scala.collection.AbstractIterator.concat(Iterator.scala:1293)
	at scala.collection.Iterator.$plus$plus(Iterator.scala:620)
	at scala.collection.Iterator.$plus$plus$(Iterator.scala:620)
	at scala.collection.AbstractIterator.$plus$plus(Iterator.scala:1293)
	at com.fulcrumgenomics.bam.Template.primaryReads(Bams.scala:63)
	at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:152)
	at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$$$Lambda$359/675889995.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$Lambda$357/2259527.apply$mcV$sp(Unknown Source)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
	at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
	at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$Lambda$357/2259527.apply$mcV$sp(Unknown Source)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
	at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
	at scala.collection.immutable.Vector$.from(Vector.scala:1349)

**Comment by nh13** [comment]
Try using `--max-reads` to limit the number of reads used in consensus calling.  See: http://fulcrumgenomics.github.io/fgbio/tools/latest/CallMolecularConsensusReads.html

**Comment by bebelya** [comment]
That worked! Thank you so much for a quick response!

**Comment by nh13** [comment]
@bebelya the answer is in the link I sent and in the usage on the command line!

**Comment by bebelya** [comment]
Thanks!
