### ISSUE TITLE
CallMolecularConsensusReads failing 

### ISSUE THREAD

**Issue by ChadAHighfill** [fulcrumgenomics/fgbio#870]
Hi Team, 

I am running fgbio CallMolecularConsensusReads. But this fails after starting for a bit. I am unsure what the issue is. I first sorted bam via Queryname, add MI tags via SetMateInformation, then grouped reads by UMI. Thus, I should have all the required inform to run this command. 

[2022/08/10 14:03:55 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 2.0.0 as Person on JRE 1.8.0_211-b12 with snappy, IntelInflater, and IntelDeflater
[2022/08/10 14:03:56 | CallMolecularConsensusReads | Info] Seen many non-increasing record positions. Printing Read-names as well.
[2022/08/10 14:04:45 | CallMolecularConsensusReads | Info] processed     1,000,000 records.  Elapsed time: 00:00:49s.  Time for last 1,000,000:   49s.  Last read position: chr1:10,399,164.  Last read name: A00423:160:H2L3LDSX3:4:1530:14760:9580
[2022/08/10 14:05:13 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 1.33 minutes.
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.$anonfun$next$1(ReadAndRefPosIterator.scala:97)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:71)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.FgBioDef$.yieldAndThen(FgBioDef.scala:37)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:98)
        at com.fulcrumgenomics.bam.ReadAndRefPosIterator.next(ReadAndRefPosIterator.scala:49)
        at scala.collection.Iterator$$anon$1.next(Iterator.scala:145)
        at scala.collection.Iterator$$anon$1.head(Iterator.scala:126)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:80)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller.call(OverlappingBasesConsensusCaller.scala:61)
        at com.fulcrumgenomics.bam.OverlappingBasesConsensusCaller$.$anonfun$iterator$1(OverlappingBasesConsensusCaller.scala:169)
        at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:944)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1565)
        at scala.collection.immutable.Vector$.from(Vector.scala:1349)
        at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.IndexedSeq$.from(Seq.scala:115)
        at scala.collection.IterableOnceOps.toIndexedSeq(IterableOnce.scala:1265)
        at scala.collection.IterableOnceOps.toIndexedSeq$(IterableOnce.scala:1265)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.toIndexedSeq(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1(ConsensusCallingIterator.scala:111)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.$anonfun$advance$1$adapted(ConsensusCallingIterator.scala:109)
        at scala.Option.exists(Option.scala:406)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.advance(ConsensusCallingIterator.scala:109)
        at com.fulcrumgenomics.umi.SamRecordGroupedIterator.hasNext(ConsensusCallingIterator.scala:99)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:594)
        at com.fulcrumgenomics.umi.ConsensusCallingIterator.hasNext(ConsensusCallingIterator.scala:79)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at com.fulcrumgenomics.umi.ConsensusCallingIterator.foreach(ConsensusCallingIterator.scala:45)
        at com.fulcrumgenomics.commons.io.Writer.write(Writer.scala:36)
        at com.fulcrumgenomics.commons.io.Writer.write$(Writer.scala:36)
        at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:109)
        at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq(Writer.scala:46)
        at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq$(Writer.scala:45)
        at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:109)
        at com.fulcrumgenomics.umi.CallMolecularConsensusReads.execute(CallMolecularConsensusReads.scala:182)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by ChadAHighfill** [comment]
Code I am calling:
java -Xmx110g -jar /data/highfillca/Tools/fgbio-2.0.0.jar CallMolecularConsensusReads \
    --input=PATH/TO/MQ.grouped.QsortedUMI.bam \
    --min-reads=1 \
    --error-rate-post-umi=30 \
    --output=/PATH/FROM/MQ.consensus.grouped.QsortedUMI.bam

**Comment by nh13** [comment]
Try with 2.0.2.  See similar issues: https://github.com/fulcrumgenomics/fgbio/issues?q=java.util.NoSuchElementException%3A+None.get

**Comment by ChadAHighfill** [comment]
You can close. 2.0.2 worked.
