### ISSUE TITLE
SetMateInformation failed

### ISSUE THREAD

**Issue by SR5590** [fulcrumgenomics/fgbio#883]
Hi, 

I am using the fgbio script in my snakemake pipeline. Here I have added the description of the pipeline, so take a look and let me know if something is wrong.

```
rule Samtools:
    input:
        bam="../03_star/{sample}Aligned.sortedByCoord.out.bam",
        r_umi="../02_trim/{sample}_umis_1P.fastq.gz",
    output:
        index="../03_star/{sample}Aligned.sortedByCoord.out.bam.bai",
        anno="../03_star/{sample}/{sample}_anno.bam",
        sorted="../03_star/{sample}_fgbioSorted.bam",
        CallCons="../03_star/{sample}_CallCons.bam",
        GroupRead="../03_star/{sample}_GroupRead.bam",
        r1_out="../03_star/UmiReads/{sample}_umiReads_1P.fastq.gz",
        r2_out="../03_star/UmiReads/{sample}_umiReads_2P.fastq.gz",
    threads:8
    
conda: "envs/samtools.yaml"
    shell:"samtools index {input.bam} ;\
           fgbio -XX:-UseGCOverheadLimit -Xms750m -Xmx32g --tmp-dir=../{wildcards.sample}/tmp/  AnnotateBamWithUmis -i {input.bam} -f {input.r_umi}  -o {output.anno} ;\
           fgbio -XX:-UseGCOverheadLimit -Xms750m -Xmx32g --tmp-dir=../{wildcards.sample}/tmp/ SortBam -i {output.anno} -s Queryname -o {output.sorted} ;\
           fgbio -XX:-UseGCOverheadLimit -Xms750m -Xmx32g --tmp-dir=../{wildcards.sample}/tmp/ SetMateInformation -i {output.sorted} -x true | \
           fgbio -XX:-UseGCOverheadLimit -Xms750m -Xmx32g --tmp-dir=../{wildcards.sample}/tmp/  GroupReadsByUmi --edits=1 --min-map-q=1 -t RX -s adjacency -o {output.GroupRead}; \
           fgbio -XX:-UseGCOverheadLimit -Xms750m -Xmx32g  --tmp-dir=../{wildcards.sample}/tmp/ CallMolecularConsensusReads --min-input-base-quality=2 --min-reads=1 --max-reads=1000000 \
           --output-per-base-tags=false --sort-order=:none: -i {output.GroupRead} -o {output.CallCons} ; \
           samtools fastq -1 {output.r1_out} -2 {output.r2_out} {output.CallCons} "
```

I am getting this error when the pipeline runs the SetMateInformation command. Please take a look at it and help me solve this issue.

> | FgBioMain | Info] Executing SetMateInformation from fgbio version 1.3.0 as (@servername) on JRE 1.8.0_152-release-1056-b12 with snappy, IntelInflater, and IntelDeflater
> | FgBioMain | Info] SetMateInformation failed. Elapsed time: 0,06 minutes.
> Exception in thread "main" htsjdk.samtools.SAMException: Found two records that are paired, not supplementary, and first of the pair: NB552094:195:HGLLGBGXH:1:11101:10001
> 	at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.advance(SamPairUtil.java:454)
> 	at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.next(SamPairUtil.java:501)
> 	at htsjdk.samtools.SamPairUtil$SetMateInfoIterator.next(SamPairUtil.java:388)
> 	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.next(CommonsDef.scala:251)
> 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
> 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
> 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
> 	at com.fulcrumgenomics.commons.io.Writer.write(Writer.scala:36)
> 	at com.fulcrumgenomics.commons.io.Writer.write$(Writer.scala:36)
> 	at com.fulcrumgenomics.bam.api.SamWriter.write(SamWriter.scala:107)
> 	at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq(Writer.scala:46)
> 	at com.fulcrumgenomics.commons.io.Writer.$plus$plus$eq$(Writer.scala:45)
> 	at com.fulcrumgenomics.bam.api.SamWriter.$plus$plus$eq(SamWriter.scala:107)
> 	at com.fulcrumgenomics.bam.SetMateInformation.execute(SetMateInformation.scala:68)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
> 	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by nh13** [comment]
> Found two records that are paired, not supplementary, and first of the pair: NB552094:195:HGLLGBGXH:1:11101:10001

Can you examine at the read pair with this name, and see where the primary alignments got lost?

**Comment by nh13** [comment]
Since you used `-x`, it makes me even more suspicious about a primary alignment getting lost.  Please feel free to re-open if you have more info on this issue.
