### ISSUE TITLE
Error:Could not find dictionary next to reference file

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#885]
Hi,

I'm getting the below error in the best practices uBam -> Mapped BAM step. fgbio 2.0.2

All the bwa index files are present in the same directory as the .fa file, and also a .fai file
```
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 2958872 reads in 2481.994 CPU sec, 208.807 real sec
[2022/11/21 17:33:09 | ZipperBams | Warning] input file /dev/stdin does not appear to be queryname sorted or grouped.
[2022/11/21 17:33:09 | ZipperBams | Warning] Continuing, but your output may be incorrect.
[2022/11/21 17:33:09 | FgBioMain | Info] ZipperBams failed. Elapsed time: 3.57 minutes.
Exception in thread "main" htsjdk.samtools.SAMException: Could not find dictionary next to reference file file:///gpfs/data/reference-files/mm10/mm10.fa
        at htsjdk.variant.utils.SAMSequenceDictionaryExtractor$TYPE$1.extractDictionary(SAMSequenceDictionaryExtractor.java:58)
        at htsjdk.variant.utils.SAMSequenceDictionaryExtractor.extractDictionary(SAMSequenceDictionaryExtractor.java:170)
        at com.fulcrumgenomics.bam.ZipperBams.execute(ZipperBams.scala:221)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

**Comment by gevro** [comment]
I found the solution, apparently a .dict file is required for each reference:
https://gatk.broadinstitute.org/hc/en-us/articles/360037422891-CreateSequenceDictionary-Picard-

**Comment by nh13** [comment]
`samtools dict` also supports generating one!
