### ISSUE TITLE
Allow Bypass of assertCanWriteFile

### ISSUE THREAD

**Issue by greenbagels** [fulcrumgenomics/fgbio#942]
Hello and thanks for this tool!

Our clinical lab is trying to implement fgbio in a containerized sequencing pipeline that handles UMI-tagged reads; to do so, I've packaged fgbio in a Docker image based on Temurin; the code seems to be working fine except for one small issue:

```
Exception in thread "main" java.lang.AssertionError: assertion failed: Cannot write file because parent directory is not writable: /mgps-data/ngs_runs/miseq/231003_M07812_0018_000000000-K72W2/bams/sample.umi_rejected.bam

        at scala.Predef$.assert(Predef.scala:279)
        at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile(Io.scala:164)
        at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile$(Io.scala:150)
        at com.fulcrumgenomics.util.Io.assertCanWriteFile(Io.scala:38)
        at com.fulcrumgenomics.umi.CorrectUmis.$anonfun$new$2(CorrectUmis.scala:144)
        at com.fulcrumgenomics.umi.CorrectUmis.$anonfun$new$2$adapted(CorrectUmis.scala:144)
        at scala.Option.foreach(Option.scala:437)
```

Our thoughts: our storage infrastructure utilizes NFS, and maybe the discrepancy between NFS ACLs and POSIX read-write permissions might be confusing fgbio into thinking it doesn't have write permissions when it does.

We've already done some testing to rule out permissions issues with the container itself (we can echo to files in the parent directory just fine), so we're wondering if it would be possible to request some kind of assert-bypassing flag (to force blind writes). If you have any questions or requests for more info, I'd be happy to oblige!

**Comment by cehtolonen** [comment]
Hello @greenbagels - apologies for the delayed response. Is this still an issue for you? Thank you.

**Comment by cehtolonen** [comment]
Hello @greenbagels, please re-open later if this is still an issue for you. Thanks!
