### ISSUE TITLE
CallMolecularConsensus Fails 

### ISSUE THREAD

**Issue by jmd5596** [fulcrumgenomics/fgbio#973]
Hello

I have created a pipeline for single stranded UMI consensus sequencing that has worked with previous batch samples. However when performing CallMolecularConsensusRead on my bam file I get the following error.
fgbio --compression 0 CallMolecularConsensusReads -i "${JDIRECTORY_PATH}/fix/${SAMPLE_PREFIX}_${SLURM_ARRAY_TASK_ID}_grouped_unmapped.bam" --rejects "${JDIRECTORY_PATH}/fix/${SAMPLE_PREFIX}_${SLURM_ARRAY_TASK_ID}_reject.bam" --output "${JDIRECTORY_PATH}/fix/${SAMPLE_PREFIX}_${SLURM_ARRAY_TASK_ID}_tmp.bam" --min-input-base-quality 10 --error-rate-post-umi 30 --threads 3 --min-reads 3 --debug

[2024/03/15 15:25:39 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 0.08 minutes.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 131001 out of bounds f
or byte[65518]
        at java.base/java.lang.System.arraycopy(Native Method)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:129)

I have already checked the input bam with ValidateSamFile and there are no errors can someone please help. I am at a total loss :(

**Comment by nh13** [comment]
What version of Java are you using?  Could you try a different version of Java?  

I don't think this is related to the tool itself.  Do you have others within your organization that can help you?  Feel free to reach out to us if you'd like paid support (www.fulcrumgenomics.com)

**Comment by jmd5596** [comment]
Hello, I am using a ssh cluster from my institution, the java version is 
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode).

Maybe it needs to update? Unfortunately there isn't anyone in my department that is familiar with bioinformatics.

**Comment by nh13** [comment]
@jmd5596 you may try installing a different version (e.g. with conda) of openjdk and see if that resolves it?  In my experience, this error is due to the Java version installed.  Perhaps try java 1.8.0.

**Comment by jmd5596** [comment]
Alright, it must be a java issue then because I did the update to java 1.8 and re-ran the tool and got this error: 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/fulcrumgenomics/cmdline/FgBioMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
