### ISSUE TITLE
Non existent path error when using FastqToBam with links

### ISSUE THREAD

**Issue by shashwatsahay** [fulcrumgenomics/fgbio#984]
Hi 

I keep getting AssertionError when using links instead of absolute file path when using FastqToBam

Any insights here will be helpful

Exception in thread "main" java.lang.AssertionError: assertion failed: Cannot read non-existent path: /home/user/sample_R1_L1.fastq.gz
	at scala.Predef$.assert(Predef.scala:279)
	at com.fulcrumgenomics.commons.io.IoUtil.assertReadable(Io.scala:115)
	at com.fulcrumgenomics.commons.io.IoUtil.assertReadable$(Io.scala:113)
	at com.fulcrumgenomics.util.Io.assertReadable(Io.scala:38)
	at com.fulcrumgenomics.commons.io.IoUtil.$anonfun$assertReadable$1(Io.scala:110)
	at com.fulcrumgenomics.commons.io.IoUtil.$anonfun$assertReadable$1$adapted(Io.scala:110)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1293)
	at com.fulcrumgenomics.commons.io.IoUtil.assertReadable(Io.scala:110)
	at com.fulcrumgenomics.commons.io.IoUtil.assertReadable$(Io.scala:110)
	at com.fulcrumgenomics.util.Io.assertReadable(Io.scala:38)
	at com.fulcrumgenomics.fastq.FastqToBam.<init>(FastqToBam.scala:113)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.fulcrumgenomics.commons.reflect.ReflectiveBuilder.build(ReflectiveBuilder.scala:161)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineProgramParser.parseAndBuild(CommandLineProgramParser.scala:149)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineParser.parseSubCommand(CommandLineParser.scala:312)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineParser.parseCommandAndSubCommand(CommandLineParser.scala:412)
	at com.fulcrumgenomics.sopt.Sopt$.parseCommandAndSubCommand(Sopt.scala:159)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:113)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by shashwatsahay** [comment]
I just solved it, was using a singularity containier without mounting the file system. Sorry
